### PR TITLE
Add QR codes for all certificates

### PR DESCRIPTION
**Pull request by adipata**

### CODE REVIEW

**Review by SchulzeStTSI — CHANGES_REQUESTED** [review]
@adipata 

Can you please follow the RAW structure of JSON, CBOR etc? Currently is just the plain JSON in the file

**Comment by SchulzeStTSI** [comment]
@adipata The QRs are also not tagged: 

image

**Comment by adipata** [comment]
RAW files generated according to specifications.

**Comment by SchulzeStTSI** [comment]
@adipata Thank you very much. Can you fix the tagging as well?

**Comment by adipata** [comment]
I added the TAG18 but still the tests do not pass. I looked a little on results and I find an error saying:
 E   urllib.error.HTTPError: HTTP Error 404: Not Found
It does not tell me much.

**Comment by daniel-eder** [comment]
@adipata There seems to be an issue with the URL hosting the JSON Schema, leading to the validation errors, see #280 
We'll have to re-run the check once the URL points to the correct schema and subschema files again

**Pull request merged**
