### PR TITLE
Slovenian test data

### PR DESCRIPTION
**Pull request by DragoMlakar**
Slovenian test data. First attempt. Used Sweden java code @martin-lindstrom and change data, crypto material. 
Will add more tests to cover additional variation of input data.

### CODE REVIEW

**Comment by DragoMlakar** [comment]
Not quite sure how it goes... 
Are there any additional actions that must be made that this goes in review? 
Should this crypto material be registered somewhere?
@f11h

**Comment by f11h** [comment]
@SchulzeStTSI can you have a look on this?

**Comment by martin-lindstrom** [comment]
> Slovenian test data. First attempt. Used Sweden java code @martin-lindstrom and change data, crypto material.
> Will add more tests to cover additional variation of input data.

I see that you actually copied much of the things from the SE test tool (including the UVCI). Your files only makes sense if you are actually using the dgc-java library to produce your DGC. Are you? (if you are, I have no objections).

**Comment by DragoMlakar** [comment]
> > Slovenian test data. First attempt. Used Sweden java code @martin-lindstrom and change data, crypto material.
> > Will add more tests to cover additional variation of input data.
> 
> I see that you actually copied much of the things from the SE test tool (including the UVCI). Your files only makes sense if you are actually using the dgc-java library to produce your DGC. Are you? (if you are, I have no objections).

Yes. Using dgc-java to create. Changed jsons, generate new crypto material. Will add more examples.

**Review by SchulzeStTSI — APPROVED** [review]

**Pull request merged**
