### PR TITLE
Automation of dgc testdata verification

### PR DESCRIPTION
**Pull request by bhavin-qryptal**
Dear Team

We have developed scripts to run dgc testdata verification of all test JSON files against expected rules. It uses GitHub CI/CD to run tests automatically whenever a country adds/updates their test files. This would help identify all test data issues in an automated manner and help everyone comply with expected rules.

An example of current test reports available under fork 
@ https://github.com/bhavin-qryptal/dgc-testdata/runs/2628926632?check_suite_focus=true
and https://github.com/bhavin-qryptal/dgc-testdata/runs/2628942292?check_suite_focus=true

Would like to contribute this for wider benefits.

Would appreciate your feedback / suggestions for further enhancement / refinement and assistance to accept this pull request and make it a part of the process.

Regards
Bhavin Sanghvi
Qryptal Pte Ltd, Singapore

### CODE REVIEW

**Comment by martin-lindstrom** [comment]
I checked the output from your tests. A bit hard to read and figure out why the test fails.

For example. SE/5.json seems to fail, but I can not see why it fails. I am pretty sure that the testfile is OK.

**Comment by bhavin-qryptal** [comment]
> I checked the output from your tests. A bit hard to read and figure out why the test fails.
> 
> For example. SE/5.json seems to fail, but I can not see why it fails. I am pretty sure that the testfile is OK.

Thank you for the feedback. I agree that report is bit hard to read, as it contains error stack trace to assist with investigation etc. I welcome suggestions to make the reports friendlier. As of now, total three different options available to view reports online. 

The test script also support running country specific or file specific test to help with investigation.

And specifically for SE/5.json file - It is failing as COSE Payload is double tagged.  CBORTag(61, CBORTag(18, [b'\ . 
See... 
image

**Comment by martin-lindstrom** [comment]
> 
> And specifically for SE/5.json file - It is failing as COSE Payload is double tagged. CBORTag(61, CBORTag(18, [b'\ .

But that is not an error. It is an odd case, but perfectly legal. I added the testfile just to point out this.

The 61-tag is the CWT tag (that may be included), and the 18-tag is the Cose_Sign1 tag.

See section 6 of [RFC8392](https://datatracker.ietf.org/doc/html/rfc8392).

**Comment by bhavin-qryptal** [comment]
> > And specifically for SE/5.json file - It is failing as COSE Payload is double tagged. CBORTag(61, CBORTag(18, [b'\ .
> 
> But that is not an error. It is an odd case, but perfectly legal. I added the testfile just to point out this.
> 
> The 61-tag is the CWT tag (that may be included), and the 18-tag is the Cose_Sign1 tag.
> 
> See section 6 of [RFC8392](https://datatracker.ietf.org/doc/html/rfc8392).

Thank you for the enlightenment. I will fix the validation script and update the pull request soon.

**Comment by bhavin-qryptal** [comment]
> The 61-tag is the CWT tag (that may be included), and the 18-tag is the Cose_Sign1 tag.
> 
> See section 6 of [RFC8392](https://datatracker.ietf.org/doc/html/rfc8392).

I have made change in the test script now. With that, all tests for SE/5.json are passing except one KID verification test. 

Given KID on the message does not match with derived KID.
Expected :b'_t\x91\x01\x95\xc5\xce\xcb' 
Actual   :b'\x19\x9d\x9c|\xc2\xf0\xc8\xaf'

Reference: https://github.com/bhavin-qryptal/dgc-testdata/runs/2629388452?check_suite_focus=true

**Comment by daniel-eder** [comment]
@bhavin-qryptal Thank you! 
@SchulzeStTSI can you take a look at this?

**Review by chrloch — CHANGES_REQUESTED** [review]
Hi, 

Thank you very much for contributing to our project. The test suite looks very good.
I just noticed that 'test_ehealth_certs.py' contains some hard coded xfails based on known issues.
Marking such tests as xfail is a good practice but I feel that the list of countries, affected tests and issues should not be part of the test code itself but rather belongs into a config file.

best regards
Christian

**Comment by bhavin-qryptal** [comment]
> Marking such tests as xfail is a good practice but I feel that the list of countries, affected tests and issues should not be part of the test code itself but rather belongs into a config file.

Thank you very much for your feedback. This indeed is a good idea. I would work on this and make amendments as per this suggestion.

**Comment by bhavin-qryptal** [comment]
> I just noticed that 'test_ehealth_certs.py' contains some hard coded xfails based on known issues.
> Marking such tests as xfail is a good practice but I feel that the list of countries, affected tests and issues should not be part of the test code itself but rather belongs into a config file.

This is now implemented. Please have a look. Thank you for the feedback.

**Comment by bhavin-qryptal** [comment]
> I checked the output from your tests. A bit hard to read and figure out why the test fails.

Now we have got optimized / easy to process brief log output. Reference: https://github.com/bhavin-qryptal/dgc-testdata/runs/2635146925?check_suite_focus=true
Each expected failure provides link to the GitHub issue in the log.  

image

**Comment by chrloch** [comment]
Looks really good like this, IMO

**Comment by bhavin-qryptal** [comment]
> IMO

Thank you. Would like to get feedback from more and help accepting this pull request.

**Comment by daniel-eder** [comment]
> > IMO
> 
> Thank you. Would like to get feedback from more and help accepting this pull request.

@bhavin-qryptal Thank you again for your contribution.
There is one consideration: Would you be opposed to licensing your contribution under the Apache 2.0 license? There would then be a specific notice file in the root level, that lists your contribution.

The reason is simply to keep a unified license choice over all parts of the project, and we agreed toward the EC to use the Apache 2.9. If you prefer to keep the contribution under MIT, then that's not an issue either, of course, as both are permissive and compatible. 

Let me know what your thoughts are!

**Comment by bhavin-qryptal** [comment]
> There is one consideration: Would you be opposed to licensing your contribution under the Apache 2.0 license? There would then be a specific notice file in the root level, that lists your contribution.

Thank you @daniel-eder.

Apache 2.0 license is good with us. I have modified the license section in the code file and pushed it in. Please let me know if anything else needs to be done. 

Thank you once again.

**Comment by SchulzeStTSI** [comment]
@bhavin-qryptal Does your automation scripts handle the "common" Folder seperatly? We would like to add edge cases which very specific problems in the future.

**Comment by daniel-eder** [comment]
> > There is one consideration: Would you be opposed to licensing your contribution under the Apache 2.0 license? There would then be a specific notice file in the root level, that lists your contribution.
> 
> Thank you @daniel-eder.
> 
> Apache 2.0 license is good with us. I have modified the license section in the code file and pushed it in. Please let me know if anything else needs to be done.
> 
> Thank you once again.

Perfect, thank you!

**Comment by bhavin-qryptal** [comment]
> @bhavin-qryptal Does your automation scripts handle the "common" Folder seperatly? We would like to add edge cases which very specific problems in the future.

Test script test validate all folders common as well as country specific one. Let me know if any additional changes are needed. As of now, we plan to add:
1. Include ValueSet validation (currently not implemented). Let me know if you know any Python library which I could integrate to achieve this easily.
2. Additional business rule validations (e.g. validate UVCI is valid or not) 

Idea is to make current version available for wider community benefit and keep on enhancing that collectively.

**Comment by bhavin-qryptal** [comment]
@daniel-eder , @SchulzeStTSI 
To add, with help of these scripts we were able to find out number of issues in current scripts, raise tickets for each country. Each country could do self verification once we make this test part of the workflow. May be we could run this script before accepting each pull request to eliminate some noise.

**Comment by dslmeinte** [comment]
@bhavin-qryptal I'm currently working on implementing the [business rules specified here](https://webgate.ec.europa.eu/fpfis/wikis/display/eHN/EU+Level+Business+Rules) using JsonLogic. I want to check that JsonLogic is a fit for JS evaluation, and then extend to use the Python and Swift implementations as well. (I'm not 100% sure whether JsonLogic really works.)

**Comment by bhavin-qryptal** [comment]
> @bhavin-qryptal I'm currently working on implementing the [business rules specified here](https://webgate.ec.europa.eu/fpfis/wikis/display/eHN/EU+Level+Business+Rules) using JsonLogic. I want to check that JsonLogic is a fit for JS evaluation, and then extend to use the Python and Swift implementations as well. (I'm not 100% sure whether JsonLogic really works.)

Thank you Meinte for sharing this. If you could, do share link to WIP version of JsonLogic you are working on. Also, I dont have access to https://webgate.ec.europa.eu/fpfis/wikis/display/eHN/EU+Level+Business+Rules, Are you aware of any free to access equivalent document OR guide me with process to get access? 

Regards
Bhavin

**Comment by dslmeinte** [comment]
@bhavin-qryptal Let me wrestle with JsonLogic until 13:30, before I start sharing stuff that we can/should bin anyway. I'll check for access - brb.

**Comment by SchulzeStTSI** [comment]
@dslmeinte @bhavin-qryptal This version is foreseen: https://github.com/jwadhams/json-logic-js/ But there is still investigation how dates can be proceed in the best way or which functions must be applied to the code. I would appreciate some feedback. Especially for kotlin and swift.

**Comment by dslmeinte** [comment]
@SchulzeStTSI That's the one I'm working with to implement the business rules you and Vincent write down. I have some concerns though, because it's not entirely plain sailing, and not for splendid reasons.

Nevertheless: I think the idea of using a cross-platform logic engine (executing JSON) is fundamentally sound.

You want to set up a quick meet with Vincent, and us 2 to discuss the Confluence-page including JsonLogic?

**Comment by daniel-eder** [comment]
@bhavin-qryptal Thank you again for your contribution. We merged the current version (with one change, we forked the third party action), and we'll run it on future pull requests.

Feedback and improvements are very welcome!

**Comment by bhavin-qryptal** [comment]
Thank you very much @daniel-eder

**Pull request merged**
