### PR TITLE
Iceland First test data

### PR DESCRIPTION
**Pull request by gunnarif**

### CODE REVIEW

**Review by SchulzeStTSI — COMMENTED** [review]
@gunnarif Can you please move then png folder to IS/2DCode?

**Comment by gunnarif** [comment]
@SchulzeStTSI done
also fixed some small issue

**Review by SchulzeStTSI — APPROVED** [review]

**Comment by martin-lindstrom** [comment]
@gunnarif Sweden can successfully parse and validate your data.

Just a minor thing. The validationclock does not hold a valid ISO-8601 string. Corrected that manually.

**Comment by gunnarif** [comment]
@martin-lindstrom  thanks, I will fix it 
I can also verify SE data

**Pull request merged**
