### PR TITLE
Inserted San Marino tests JSON 1.0.0

### PR DESCRIPTION
**Pull request by fegrasso**

### CODE REVIEW

**Comment by daniel-eder** [comment]
@fegrasso it looks like there's an issue with the UTF8 encoding: ` json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)`

**Comment by fegrasso** [comment]
> @fegrasso it looks like there's an issue with the UTF8 encoding: ` json.decoder.JSONDecodeError: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)`

@daniel-eder I fixed issue. Let me know. Thanks

**Comment by daniel-eder** [comment]
@fegrasso The JSONs correctly loaded this time, but the tests now found some issues with the content, can you take a look:

```
____________________ test_cose_schema[SM/2DCode/raw/4.json] ____________________
tests/test_ehealth_certs.py:287: in test_cose_schema
    schema_validate(hcert, _get_hcert_schema())
/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jsonschema/validators.py:934: in validate
    raise error
E   jsonschema.exceptions.ValidationError: [] is too short
E   
E   Failed validating 'minItems' in schema['properties']['t']:
E       {'description': 'Test Group',
E        'items': {'description': 'Test Entry',
E                  'properties': {'ci': {'description': 'Certificate '
E                                                       'Identifier, format as '
E                                                       'per UVCI: Annex 2 in  '
E                                                       'https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'co': {'description': 'Country of '
E                                                       'Vaccination / Test, '
E                                                       'ISO 3166 where '
E                                                       'possible',
E                                        'pattern': '[A-Z]{1,10}',
E                                        'type': 'string'},
E                                 'dr': {'description': 'Date/Time of Test '
E                                                       'Result',
E                                        'format': 'date-time',
E                                        'type': 'string'},
E                                 'is': {'description': 'Certificate Issuer',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'ma': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.8',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-manf.json'},
E                                 'nm': {'description': 'NAA Test Name',
E                                        'type': 'string'},
E                                 'sc': {'description': 'Date/Time of Sample '
E                                                       'Collection',
E                                        'format': 'date-time',
E                                        'type': 'string'},
E                                 'tc': {'description': 'Testing Centre',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'tg': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.1',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/disease-agent-targeted.json'},
E                                 'tr': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.9',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-results.json'},
E                                 'tt': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.7',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-type.json'}},
E                  'required': ['tg', 'tt', 'sc', 'tr', 'tc', 'co', 'is', 'ci'],
E                  'type': 'object'},
E        'minItems': 1,
E        'type': 'array'}
E   
E   On instance['t']:
E       []
____________________ test_cose_schema[SM/2DCode/raw/1.json] ____________________
tests/test_ehealth_certs.py:287: in test_cose_schema
    schema_validate(hcert, _get_hcert_schema())
/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jsonschema/validators.py:934: in validate
    raise error
E   jsonschema.exceptions.ValidationError: [] is too short
E   
E   Failed validating 'minItems' in schema['properties']['t']:
E       {'description': 'Test Group',
E        'items': {'description': 'Test Entry',
E                  'properties': {'ci': {'description': 'Certificate '
E                                                       'Identifier, format as '
E                                                       'per UVCI: Annex 2 in  '
E                                                       'https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'co': {'description': 'Country of '
E                                                       'Vaccination / Test, '
E                                                       'ISO 3166 where '
E                                                       'possible',
E                                        'pattern': '[A-Z]{1,10}',
E                                        'type': 'string'},
E                                 'dr': {'description': 'Date/Time of Test '
E                                                       'Result',
E                                        'format': 'date-time',
E                                        'type': 'string'},
E                                 'is': {'description': 'Certificate Issuer',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'ma': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.8',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-manf.json'},
E                                 'nm': {'description': 'NAA Test Name',
E                                        'type': 'string'},
E                                 'sc': {'description': 'Date/Time of Sample '
E                                                       'Collection',
E                                        'format': 'date-time',
E                                        'type': 'string'},
E                                 'tc': {'description': 'Testing Centre',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'tg': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.1',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/disease-agent-targeted.json'},
E                                 'tr': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.9',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-results.json'},
E                                 'tt': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.7',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-type.json'}},
E                  'required': ['tg', 'tt', 'sc', 'tr', 'tc', 'co', 'is', 'ci'],
E                  'type': 'object'},
E        'minItems': 1,
E        'type': 'array'}
E   
E   On instance['t']:
E       []
____________________ test_cose_schema[SM/2DCode/raw/2.json] ____________________
tests/test_ehealth_certs.py:287: in test_cose_schema
    schema_validate(hcert, _get_hcert_schema())
/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jsonschema/validators.py:934: in validate
    raise error
E   jsonschema.exceptions.ValidationError: [] is too short
E   
E   Failed validating 'minItems' in schema['properties']['t']:
E       {'description': 'Test Group',
E        'items': {'description': 'Test Entry',
E                  'properties': {'ci': {'description': 'Certificate '
E                                                       'Identifier, format as '
E                                                       'per UVCI: Annex 2 in  '
E                                                       'https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'co': {'description': 'Country of '
E                                                       'Vaccination / Test, '
E                                                       'ISO 3166 where '
E                                                       'possible',
E                                        'pattern': '[A-Z]{1,10}',
E                                        'type': 'string'},
E                                 'dr': {'description': 'Date/Time of Test '
E                                                       'Result',
E                                        'format': 'date-time',
E                                        'type': 'string'},
E                                 'is': {'description': 'Certificate Issuer',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'ma': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.8',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-manf.json'},
E                                 'nm': {'description': 'NAA Test Name',
E                                        'type': 'string'},
E                                 'sc': {'description': 'Date/Time of Sample '
E                                                       'Collection',
E                                        'format': 'date-time',
E                                        'type': 'string'},
E                                 'tc': {'description': 'Testing Centre',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'tg': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.1',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/disease-agent-targeted.json'},
E                                 'tr': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.9',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-results.json'},
E                                 'tt': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.7',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-type.json'}},
E                  'required': ['tg', 'tt', 'sc', 'tr', 'tc', 'co', 'is', 'ci'],
E                  'type': 'object'},
E        'minItems': 1,
E        'type': 'array'}
E   
E   On instance['t']:
E       []
____________________ test_cose_schema[SM/2DCode/raw/3.json] ____________________
tests/test_ehealth_certs.py:287: in test_cose_schema
    schema_validate(hcert, _get_hcert_schema())
/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jsonschema/validators.py:934: in validate
    raise error
E   jsonschema.exceptions.ValidationError: [] is too short
E   
E   Failed validating 'minItems' in schema['properties']['t']:
E       {'description': 'Test Group',
E        'items': {'description': 'Test Entry',
E                  'properties': {'ci': {'description': 'Certificate '
E                                                       'Identifier, format as '
E                                                       'per UVCI: Annex 2 in  '
E                                                       'https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'co': {'description': 'Country of '
E                                                       'Vaccination / Test, '
E                                                       'ISO 3166 where '
E                                                       'possible',
E                                        'pattern': '[A-Z]{1,10}',
E                                        'type': 'string'},
E                                 'dr': {'description': 'Date/Time of Test '
E                                                       'Result',
E                                        'format': 'date-time',
E                                        'type': 'string'},
E                                 'is': {'description': 'Certificate Issuer',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'ma': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.8',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-manf.json'},
E                                 'nm': {'description': 'NAA Test Name',
E                                        'type': 'string'},
E                                 'sc': {'description': 'Date/Time of Sample '
E                                                       'Collection',
E                                        'format': 'date-time',
E                                        'type': 'string'},
E                                 'tc': {'description': 'Testing Centre',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'tg': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.1',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/disease-agent-targeted.json'},
E                                 'tr': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.9',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-results.json'},
E                                 'tt': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.7',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-type.json'}},
E                  'required': ['tg', 'tt', 'sc', 'tr', 'tc', 'co', 'is', 'ci'],
E                  'type': 'object'},
E        'minItems': 1,
E        'type': 'array'}
E   
E   On instance['t']:
E       []
____________________ test_cose_schema[SM/2DCode/raw/5.json] ____________________
tests/test_ehealth_certs.py:287: in test_cose_schema
    schema_validate(hcert, _get_hcert_schema())
/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jsonschema/validators.py:934: in validate
    raise error
E   jsonschema.exceptions.ValidationError: [] is too short
E   
E   Failed validating 'minItems' in schema['properties']['t']:
E       {'description': 'Test Group',
E        'items': {'description': 'Test Entry',
E                  'properties': {'ci': {'description': 'Certificate '
E                                                       'Identifier, format as '
E                                                       'per UVCI: Annex 2 in  '
E                                                       'https://ec.europa.eu/health/sites/health/files/ehealth/docs/vaccination-proof_interoperability-guidelines_en.pdf',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'co': {'description': 'Country of '
E                                                       'Vaccination / Test, '
E                                                       'ISO 3166 where '
E                                                       'possible',
E                                        'pattern': '[A-Z]{1,10}',
E                                        'type': 'string'},
E                                 'dr': {'description': 'Date/Time of Test '
E                                                       'Result',
E                                        'format': 'date-time',
E                                        'type': 'string'},
E                                 'is': {'description': 'Certificate Issuer',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'ma': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.8',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-manf.json'},
E                                 'nm': {'description': 'NAA Test Name',
E                                        'type': 'string'},
E                                 'sc': {'description': 'Date/Time of Sample '
E                                                       'Collection',
E                                        'format': 'date-time',
E                                        'type': 'string'},
E                                 'tc': {'description': 'Testing Centre',
E                                        'maxLength': 50,
E                                        'type': 'string'},
E                                 'tg': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.1',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/disease-agent-targeted.json'},
E                                 'tr': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.9',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-results.json'},
E                                 'tt': {'description': 'EU eHealthNetwork: '
E                                                       'Value Sets for '
E                                                       'Digital Green '
E                                                       'Certificates. version '
E                                                       '1.0, 2021-04-16, '
E                                                       'section 2.7',
E                                        'type': 'string',
E                                        'valueset-uri': 'valuesets/test-type.json'}},
E                  'required': ['tg', 'tt', 'sc', 'tr', 'tc', 'co', 'is', 'ci'],
E                  'type': 'object'},
E        'minItems': 1,
E        'type': 'array'}
E   
E   On instance['t']:
E       []
________________ test_expected_key_usage[SM/2DCode/raw/4.json] _________________
tests/test_ehealth_certs.py:445: in test_expected_key_usage
    assert len([key for key in hcert.keys() if key in ['v', 'r', 't']]) == 1, \
E   AssertionError: DGC adheres to schema but contains multiple certificates
E   assert 3 == 1
E    +  where 3 = len(['r', 't', 'v'])
________________ test_expected_key_usage[SM/2DCode/raw/1.json] _________________
tests/test_ehealth_certs.py:445: in test_expected_key_usage
    assert len([key for key in hcert.keys() if key in ['v', 'r', 't']]) == 1, \
E   AssertionError: DGC adheres to schema but contains multiple certificates
E   assert 3 == 1
E    +  where 3 = len(['r', 't', 'v'])
________________ test_expected_key_usage[SM/2DCode/raw/2.json] _________________
tests/test_ehealth_certs.py:445: in test_expected_key_usage
    assert len([key for key in hcert.keys() if key in ['v', 'r', 't']]) == 1, \
E   AssertionError: DGC adheres to schema but contains multiple certificates
E   assert 3 == 1
E    +  where 3 = len(['r', 't', 'v'])
________________ test_expected_key_usage[SM/2DCode/raw/3.json] _________________
tests/test_ehealth_certs.py:445: in test_expected_key_usage
    assert len([key for key in hcert.keys() if key in ['v', 'r', 't']]) == 1, \
E   AssertionError: DGC adheres to schema but contains multiple certificates
E   assert 3 == 1
E    +  where 3 = len(['r', 't', 'v'])
________________ test_expected_key_usage[SM/2DCode/raw/5.json] _________________
tests/test_ehealth_certs.py:445: in test_expected_key_usage
    assert len([key for key in hcert.keys() if key in ['v', 'r', 't']]) == 1, \
E   AssertionError: DGC adheres to schema but contains multiple certificates
E   assert 3 == 1
E    +  where 3 = len(['r', 't', 'v'])
```

**Comment by fegrasso** [comment]
@daniel-eder oh sorry, I'm going to regenerate jsons without empty arrays. Thanks

**Comment by daniel-eder** [comment]
> @daniel-eder oh sorry, I'm going to regenerate jsons without empty arrays. Thanks

@fegrasso the errors at the bottom also indicate that more than one cert is included. While the schema allows that, the EU decided that only one DCC should be included per qrcode/payload

**Comment by fegrasso** [comment]
> > @daniel-eder oh sorry, I'm going to regenerate jsons without empty arrays. Thanks
> 
> @fegrasso the errors at the bottom also indicate that more than one cert is included. While the schema allows that, the EU decided that only one DCC should be included per qrcode/payload

@daniel-eder yes I know. I will solve issues

**Comment by daniel-eder** [comment]
Looks like the previous errors are no longer popping up, it currently shows a date parse issue though: [log](https://github.com/eu-digital-green-certificates/dgc-testdata/pull/347/checks?check_run_id=2885148298#step:7:94)

**Comment by fegrasso** [comment]
> Looks like the previous errors are no longer popping up, it currently shows a date parse issue though: [log](https://github.com/eu-digital-green-certificates/dgc-testdata/pull/347/checks?check_run_id=2885148298#step:7:94)

There is a Typos. I fixed instantly

**Review by daniel-eder — APPROVED** [review]

**Comment by daniel-eder** [comment]
Done! Thanks a lot!

**Comment by fegrasso** [comment]
> Done! Thanks a lot!

Thanks to you!

**Pull request merged**
