### PR TITLE
New and updated examples for Poland

### PR DESCRIPTION
**Pull request by js-pcsi**

### CODE REVIEW

**Comment by daniel-eder** [comment]
Reopened to force automated tests to run.

**Comment by daniel-eder** [comment]
@js-pcsi there are a few merge conflicts. Can you merge the latest main into your branch, choose the correct files, and push to update the PR? Thank you!

**Review by SchulzeStTSI — APPROVED** [review]

**Comment by js-pcsi** [comment]
Hello @daniel-eder, conflicts resolved

**Comment by daniel-eder** [comment]
@js-pcsi thank you!
Automatic verification found a few issues in the current state, can you look at the test result file and review it? https://github.com/eu-digital-green-certificates/dgc-testdata/suites/2821744763/artifacts/62836579 

Note: The html file, once fully loaded, allows to filter only for failed tests, there are 10 issues found. Let's make sure we get those to green before we merge, to avoid introducing new issues in the codebase :)

Thank you!

**Comment by js-pcsi** [comment]
@daniel-eder @bhavin-qryptal Verifications issues for Poland have been resolved.

**Comment by daniel-eder** [comment]
@js-pcsi thank you! Remaining failures are from NL - we introduced a regression in the known issues to be skipped. Unrelated to this PR

**Pull request merged**
