### PR TITLE
fixes #107

### LINKED ISSUE #107: NL: EXPECTEDSCHEMAVALIDATION
@wasperen2 In a lot of files did you place some values which hit the schema validation (e.g. '1963-xx-xx' does not match pattern: '(19|20)\d{2}-\d{2}-\d{2}') ) , but EXPECTEDSCHEMAVALIDATION is set to "true". What is the clear expectation on this test set? Some of that values must pass or should all fail? Can you correct the EXPECTEDSCHEMAVALIDATION values for this one which should fail during the schema validation?

### LINKED ISSUE #146: NL: EXPECTEDKEYUSAGE
**Affected Country**: NL

## Issue Description

Very high number of test files are failing EXPECTEDKEYUSAGE test. 
e.g. Test DGC Signed with a cert tagged with extended Key Usage 1.3.6.1.4.1.0.1847.2021.1.2 for Vacination Issuers. (Reference: https://github.com/eu-digital-green-certificates/dgc-overview/blob/main/guides/certificate-governance.md )

Refer to https://github.com/bhavin-qryptal/dgc-testdata/runs/2629576617?check_suite_focus=true for detailed report with such failures.

## Proposed Solution

Appropriately tagged certificates should be used to sign DGCs.

### PR DESCRIPTION
**Pull request by wasperen2**

### CODE REVIEW

**Comment by wasperen2** [comment]
* added arabic + greek given and family names
* only one type of event per case
* no XX anymore in DoB

**Comment by wasperen2** [comment]
needs further fix

**Comment by wasperen2** [comment]
still added combination events per case, does not close #146

**Comment by daniel-eder** [comment]
Reopened to force automated tests to run.

**Comment by daniel-eder** [comment]
> @daniel-eder this PR has not been merged, correct? can you please inform me what is the issue?

So sorry about that! I just intended to close & reopen to re-trigger the Workflow. Apparently I hit the button once too often

**Review by daniel-eder — APPROVED** [review]

**Pull request merged**
