### PR TITLE
new test data for GR

### PR DESCRIPTION
**Pull request by louridas**

### CODE REVIEW

**Comment by louridas** [comment]
Hello,

As far as I can tell from the report, the GR test data are OK, it is the test data from BG that are failing. Does this hold up this pull request?

**Review by SchulzeStTSI — APPROVED** [review]

**Comment by vanlooverenkoen** [comment]
How is it possible that this pull request gets merged even if the checks are failing?

**Comment by louridas** [comment]
The pull request is for the data submitted for *GR*. The checks are failing for the data submitted (previously) for BG. I reckon this data should not have been imported into the repo previously.

**Comment by vanlooverenkoen** [comment]
That is this ticket: Right? https://github.com/eu-digital-green-certificates/dgc-testdata/issues/298

**Comment by louridas** [comment]
I did not raise #298, but right now I get the same validation errors when I run:

```
/usr/bin/env pytest -C=BG
```

**Pull request merged**
