### PR TITLE
Test and recovery files from SE

### PR DESCRIPTION
**Pull request by martin-lindstrom**

### CODE REVIEW

**Comment by martin-lindstrom** [comment]
@bhavin-qryptal @SchulzeStTSI @daniel-eder I am pretty confident that the testfile 7 is OK, but the tests complain. I use the CBOR-tag 0 to indicate that this is a string-formatted date-time as specified in section [3.4.1 of RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-3.4.1). I guess this is what the test complains about.

**Comment by bhavin-qryptal** [comment]
> @bhavin-qryptal @SchulzeStTSI @daniel-eder I am pretty confident that the testfile 7 is OK, but the tests complain. I use the CBOR-tag 0 to indicate that this is a string-formatted date-time as specified in section [3.4.1 of RFC8949](https://datatracker.ietf.org/doc/html/rfc8949#section-3.4.1). I guess this is what the test complains about.

From Error Log... 
```
2021-05-25T12:05:21.8207427Z E   jsonschema.exceptions.ValidationError: datetime.datetime(2021, 5, 25, 8, 29, 51, 145008, tzinfo=datetime.timezone.utc) is not of type 'string'
2021-05-25T12:05:21.8218651Z E   
2021-05-25T12:05:21.8219600Z E   Failed validating 'type' in schema['properties']['t']['items']['properties']['sc']:
2021-05-25T12:05:21.8220560Z E       {'description': 'Date/Time of Sample Collection',
2021-05-25T12:05:21.8221293Z E        'format': 'date-time',
2021-05-25T12:05:21.8222027Z E        'type': 'string'}
```

Test is complaining that JSON Payload contains datetime value (not a string value) for field "sc" of "t". Test should pass once this value is converted into ISO string equivalent of date.

**Comment by martin-lindstrom** [comment]
But 'sc' is a date-time according to the schema:

```
"sc": {          
  "description": "Date/Time of Sample Collection",          
  "type": "string",          
 "format": "date-time"       
 },
```

**Comment by martin-lindstrom** [comment]
And my JSON looks like:
```
"sc": "2021-05-25T08:29:51.145008Z",
```

**Comment by martin-lindstrom** [comment]
And the CBOR also seems to be OK:

```
C0                             # tag(0)
        78 1B                 # text(27)
            323032312D30352D32355430383A32393A35312E3134353030385A # "2021-05-25T08:29:51.145008Z"
```

**Comment by SchulzeStTSI** [comment]
@bhavin-qryptal i think the compare has a problem. The script extracts "datetime.datetime(2021, 5, 25, 11, 21, 51, 145008, tzinfo=datetime.timezone.utc)" and compares against the isostring. Is there maybe a toIsoString() or something necessary?

**Comment by SchulzeStTSI** [comment]
@bhavin-qryptal tests/test_ehealth_certs.py:291: in test_cose_json
    assert _ordered(hcert) == _ordered(config_env[JSON])
E   AssertionError: assert [('dob', '195...er', '1.0.1')] == [('dob', '195...er', '1.0.1')]
E     At index 2 diff: ('t', [[('ci', 'URN:UVCI:01:SE:ARN/89875439877'), ('co', 'SE'), ('dr', **datetime.datetime(2021, 5, 25, 11, 21, 51, 145008, tzinfo=datetime.timezone.utc)**), ('is', 'Swedish eHealth Agency'), ('ma', '1218'), ('sc', datetime.datetime(2021, 5, 25, 8, 29, 51, 145008, tzinfo=datetime.timezone.utc)), ('tc', 'Arlanda Airport Covid Center 1'), ('tg', '840539006'), ('tr', '260415000'), ('tt', 'LP6464-4')]]) != ('t', [[('ci', 'URN:UVCI:01:SE:ARN/89875439877'), ('co', 'SE'), ('dr', **'2021-05-25T11:21:51.145008Z'**), ('is', 'Swedish eHealth Agency'), ('ma', '1218'), ('sc', '2021-05-25T08:29:51.145008Z'), ('tc', 'Arlanda Airport Covid Center 1'), ('tg', '840539006'), ('tr', '260415000'), ('tt', 'LP6464-4')]])

**Comment by bhavin-qryptal** [comment]
Here is DECODED COSE Payload for 7.json: As you could see 'sc' and 'dr' are not of type string, but 'dob' is of type string.

`{'t': [{'ci': 'URN:UVCI:01:SE:ARN/89875439877', 'co': 'SE', 'dr': datetime.datetime(2021, 5, 25, 11, 21, 51, 145008, tzinfo=datetime.timezone.utc), 'is': 'Swedish eHealth Agency', 'ma': '1218', 'sc': datetime.datetime(2021, 5, 25, 8, 29, 51, 145008, tzinfo=datetime.timezone.utc), 'tc': 'Arlanda Airport Covid Center 1', 'tg': '840539006', 'tr': '260415000', 'tt': 'LP6464-4'}], 'dob': '1958-11-11', 'nam': {'fn': 'Lövström', 'gn': 'Oscar', 'fnt': 'LOEVSTROEM', 'gnt': 'OSCAR'}, 'ver': '1.0.1'}
`
You could also compare this example with other six files where test is successful.

**Comment by bhavin-qryptal** [comment]
> @bhavin-qryptal i think the compare has a problem. The script extracts "datetime.datetime(2021, 5, 25, 11, 21, 51, 145008, tzinfo=datetime.timezone.utc)" and compares against the isostring. Is there maybe a toIsoString() or something necessary?

@SchulzeStTSI , I dont think it is comparison issue. Schema validation is also failing. Reason is that date payload is NOT of type string, but of type date.

**Comment by daniel-eder** [comment]
> @SchulzeStTSI , I dont think it is comparison issue. Schema validation is also failing. Reason is that date payload is NOT of type string, but of type date.
To clarify, the string @martin-lindstrom posted looks to me to be a valid iso date string  ("2021-05-25T08:29:51.145008Z"), but your point is that the COSE payload type is wrong? Sorry if that is obvious

**Comment by bhavin-qryptal** [comment]
> To clarify, the string @martin-lindstrom posted looks to me to be a valid iso date string ("2021-05-25T08:29:51.145008Z"), but your point is that the COSE payload type is wrong? Sorry if that is obvious

Yes, JSON Payload provided in the test is good.
COSE and CBOR Payload contains date with date data type instead of string data type.

**Comment by bhavin-qryptal** [comment]
For comparison, here is DECODED COSE Payload for IS/2DCode/raw/4.json.

`{'t': [{'ci': '01 IS/ABC4558#4', 'co': 'IS', 'dr': '2021-05-18T10:38:52Z', 'is': 'Directorate of Health of Iceland Test', 'ma': '1304', 'sc': '2021-05-18T06:38:52Z', 'tc': 'Department of ClinicalMicrobiology,Landspitali', 'tg': '840539006', 'tr': '260415000', 'tt': 'LP6464-4'}], 'dob': '2000-01-01', 'nam': {'fn': 'Testingson', 'gn': 'Testing', 'fnt': 'TESTINGSON', 'gnt': 'TESTING'}, 'ver': '1.0.0'}`

**Comment by martin-lindstrom** [comment]
Type date? There is no such type in CBOR. I tag the string representing the date-time with 0. Is this an issue with your Python-library?

**Comment by bhavin-qryptal** [comment]
> Type date? There is no such type in CBOR. I tag the string representing the date-time with 0. Is this an issue with your Python-library?

1. Would you be able to use Major Type 3 without TAG 0? 
2. Python library is able to work with DECODED COSE Payload of IS/2DCode/raw/4.json. Would you be able to compare this code with yours?

**Comment by martin-lindstrom** [comment]
@bhavin-qryptal Please read section 3.4.1 of [RFC8949](https://datatracker.ietf.org/doc/html/rfc8949).

Again. I have included the ISO-string of the date-time as a string AND tagged it with 0 according to RFC8949.

The IS-example you refer to is not tagged.

And when you are talking about the `datetime.datetime(2021, 5, 25, 8, 29, 51, 145008, tzinfo=datetime.timezone.utc`. This is your Python library being helpful (and actually recognizing the 0 tag). There is not such type in CBOR. It's a string formatted as an ISO-datetime and tagged with 0.

**Comment by martin-lindstrom** [comment]
@bhavin-qryptal @SchulzeStTSI @daniel-eder 

From https://github.com/ehn-digital-green-development/ehn-dgc-schema:

CBOR Encoding

Concise Binary Object Representation (CBOR), specified in RFC7049, defines a number of major data types. The following types are REQUIRED to be used by parties creating electronic health certificates payloads:

Integers are encoded as CBOR major type 0, an unsigned integer.
Strings are encoded as CBOR major type 3, a text string.
Arrays are encoded as CBOR major type 4, an array of data items.
Objects are encoded as CBOR major type 5, a map of pairs of data items.
**Timestamps (defined by JSON type string and format date-time) MUST be encoded as CBOR major type 3, a text string, and formatted per RFC 3339, section 5.6, with tag 0 as specified by RFC 8949, section 3.4.1.**

**Comment by SchulzeStTSI** [comment]
@martin-lindstrom I've checked now several files and everyone uses it without the tag. So it seems that nobody does that and/or no library makes a difference between date and date-time. CBOR/COSE is simply to error prone with to much windings and details which nobody knows. We should change the schema to date as the other values in test etc., because there was just date without timestamp used with data privacy explainations. The usage of date-time within the test makes no sense, and to change everything just for this tag as well not. We need here a clear line, and no fancy usage of all CBOR deep dives.

**Comment by martin-lindstrom** [comment]
> @martin-lindstrom I've checked now several files and everyone uses it without the tag. So it seems that nobody does that and/or no library makes a difference between date,date-time and string(e.g. the Jackson CBOR Mapper). CBOR/COSE is simply to error prone with to much windings and details which nobody knows. We should change the schema to date as the other values in test etc. because there was just date without timestamp used with data privacy explainations. The usage of date-time within the test makes no sense, and to change everything just for this tag as well not. We need here a clear and super rock solid line, and no fancy usage of all CBOR deep dives. Technically is it just a string and CBOR Major Type 3 works fine for the serialization of the JSON to CBOR and vice versa. I can't see the benefit to change now all implementations just to have the tag there. The test data is here since almost 4 Weeks and nobody had a problem with it.

Obviously we can't change the schema for test entries. A date simply does not have enough granularity for test entries.

Yes. A untagged string should of course be accepted, BUT, the only one following the spec should not be banned.
I am 100% sure that all CBOR-libraries understand the 0-tag. The problem here is that @bhavin-qryptal gets his timestamp in a ready to go Python object representing a date-time, but he fails to understand that the underlying encoding is a string.

I have tested parsing both untagged and tagged date-times in Java using several libraries and they all understand the 0-tag.

**Comment by martin-lindstrom** [comment]
@bhavin-qryptal So, please correct your tests.

**Comment by SchulzeStTSI** [comment]
@martin-lindstrom Maybe some java libraries support that, but you will see that not every library support it. For me is a big risk to introduce that. It will crash some implementations. We should be very very careful with things like that.

**Comment by martin-lindstrom** [comment]
> @martin-lindstrom Maybe some java libraries support that, but you will see that not every library support it. For me is a big risk to introduce that. It will crash some implementations. We should be very very careful with things like that.

Introduce? There is nothing that is to be introduced. We have an underlying standard (CBOR) and a specification (hcert-spec) that both states that 0-tag should be used for date-time strings. The specification should be followed!

Interoperability testing is about making sure that many implementations can talk to each other. Not to find a lowest common denominator.

What you are saying here is that we should ignore the specification since someone introduced a validation script. It just doesn't make sense.

**Comment by bhavin-qryptal** [comment]
@daniel-eder , 

As we have got a bit of diverse views here, I will wait for your guidance.

Please let me know if test scripts needs to modified to accommodate CBOR with Tag 0 OR you wish to keep them AS IS.

**Comment by jschlyter** [comment]
Comment as one of the principal designers of the HCERT format as well as the schema specification.

I agree with @martin-lindstrom here and I've verified the test payload using my [python-hcert](https://github.com/ehn-digital-green-development/python-hcert) library using a [test script](https://github.com/ehn-digital-green-development/python-hcert/blob/main/tools/dgc_test.py).

The schema does indeed require timestamps to be encoded as CBOR major type 3, a text string, and formatted per RFC 3339, section 5.6, with tag 0 as specified by RFC 8949, section 3.4.1. Changing this would be a significant change to the schema and very unfortunate at this time.

The test suite should be updated to conform the the specification and implementors need to output correct data.

**Comment by martin-lindstrom** [comment]
> @daniel-eder ,
> 
> As we have got a bit of diverse views here, I will wait for your guidance.
> 
> Please let me know if test scripts needs to modified to accommodate CBOR with Tag 0 OR you wish to keep them AS IS.

Rephrasing your question ;-) "Please let me know if tests scripts need to modified to actually follow the standard and specification". Just kidding, but, this is really nothing to discuss. Of course we must allow QR-codes that follow the standards.

Just for your info: My validation code (https://github.com/DIGGSweden/dgc-java) actually warns for date-times that are not tagged. Again. JSON and CBOR is similar, but there are differences. Especially when it comes to representations of timestamps, and we can't ignore the CBOR standard there.

**Comment by bhavin-qryptal** [comment]
> > @daniel-eder ,
> > As we have got a bit of diverse views here, I will wait for your guidance.
> > Please let me know if test scripts needs to modified to accommodate CBOR with Tag 0 OR you wish to keep them AS IS.
> 
> Rephrasing your question ;-) "Please let me know if tests scripts need to modified to actually follow the standard and specification". Just kidding, but, this is really nothing to discuss. Of course we must allow QR-codes that follow the standards.
> 
> Just for your info: My validation code (https://github.com/DIGGSweden/dgc-java) actually warns for date-times that are not tagged. Again. JSON and CBOR is similar, but there are differences. Especially when it comes to representations of timestamps, and we can't ignore the CBOR standard there.

Thank you, now, I do understand usage of Tag 0 and also appreciate that it is referenced in the HCERT standard. 

Question I have is:
Do we need to mandate presence of Tag 0 OR treat it as optional ? If we make it mandatory, number of other test codes would start failing validation.

**Comment by martin-lindstrom** [comment]
> > Do we need to mandate presence of Tag 0 OR treat it as optional ? If we make it mandatory, number of other test codes would start failing validation.
> 
> The specification says "MUST" so you SHALL require tag 0 in tests. Data without tag 0 is invalid and not issued according to the specification. Yes, this will render existing test vectors invalid and they need to be fixed.

IMHO validation MUST be able to handle both tagged and untagged date-times, so the test script should not give an error (or?).

**Comment by SchulzeStTSI** [comment]
@martin-lindstrom @jschlyter The issued dates are working as well without the tag. So is it really a MUST to tag it? That the verifier should support it okay, but for the issuers makes it not really a difference.

**Comment by martin-lindstrom** [comment]
> @martin-lindstrom @jschlyter The issued dates are working as well without the tag. So is it really a MUST to tag it? That the verifier should support it okay, but for the issuers makes it not really a difference.

I am in favour of being pragmatic here. If the validation script could issue a warning? Wouldn't that be enough?

**Comment by jschlyter** [comment]
> I am in favour of being pragmatic here. If the validation script could issue a warning? Wouldn't that be enough?

Yes, a strong warning that the tag is missing and that the DGC may be refused by validators.

**Comment by jschlyter** [comment]
> @martin-lindstrom @jschlyter The issued dates are working as well without the tag. So is it really a MUST to tag it? That the verifier should support it okay, but for the issuers makes it not really a difference.

Yes, timestamps MUST be tagged per specification. Sorry for being blunt, but what is the problem here - are people unable to serialize data correctly? Don't be lazy.

**Comment by SchulzeStTSI** [comment]
@martin-lindstrom @jschlyter Transforming JSON to CBOR is just a mapping. All dates are strings, so the mappers easily translate it. Tagging means to know which field is what and transfer that knowledge to the serializer. This is in some implementations a very hard task. The decoding is much easier, because the tags are already there. So it's not about being "lazy". It's about the roundtrip from JSON to CBOR and back. For the container format makes it absolutly no difference if it's tagged or not. The result is the same, because JSON is always processed, not the plain CBOR. It's just an kind of "100% spec compliant" than 99% thing. But it costs 80% of the effort. E.g. the Swift CBOR Implementations are not ready and have to be forked now, the Javascript and Pythons have to be modified as well. Just to give you an impression of the "Standard". There are a lot of implementations which simple forget the tag 0 and a string behind it, because they use a string directly.

**Comment by martin-lindstrom** [comment]
> rming JSON to CBOR is just a mapping. All dates are strings, so the mappers easily translate it. Tagging means to know which field is what and transfer that knowledge to the serializer. This is in some implementations a very hard task. The decoding is much easier, because the tags are already there. So it's not about being "lazy". It's about the roundtrip from JSON to CBOR and back. For the container format makes it absolutly no difference if it's tagged or not. The result is the same, because JSON is always processed, not the plain CBOR. It's just an kind of "100% spec compliant" than 99% thing. But it costs 80% of the effort. E.g. the Swift CBOR Implementations are not ready and have to be forked now, the Javascript and Pythons have to be modified as well. Just to give you an impression of the "Standard". There are a lot of implementations which simple forget the tag 0 and

But can we at least agree that my testfile that is encoded according to the spec should be allowed?

**Comment by SchulzeStTSI** [comment]
@martin-lindstrom It's not about your testfile. You can upload what you want. But there are people which would test against it, and they raising then the same problems by decoding. So my question would be "how important is it to be 100% spec compliant"? If the answer is, 99% percent is okay, then we align the verifiers on this special scenario and everything should be okay. 

Regarding the issuer i would like to see how you pass the informations of JSON schema to the CBOR serializer. We know just JSON to CBOR mappers which don't care about it.

**Comment by jschlyter** [comment]
@SchulzeStTSI I disagree -  it is not a _hard_ task but it may require hard work from developers equipped with non-optimal tools. I can write a correct serializer with standard tools in 30 minutes, why shouldn't other developers be able to do it within a day or two?

Just because we use JSON schema to express how the data is structured does not mean that one can just take JSON and do a 1:1 mapping to CBOR, that is not how it works. In retrospect we should perhaps have used some other schema specification language (e.g. CDDL), but for now JSON schema is what we have to work with.

**Comment by SchulzeStTSI** [comment]
@jschlyter Okay, if you have an implementation, which brings the schema and the cbor correctly together, please send me a link. Currently i know just 1:1 mappings over jackson, javascript, swift etc.

**Comment by jschlyter** [comment]
> @jschlyter Okay, if you have an implementation, which brings the schema and the cbor correctly together, please send me a link. Currently i know just 1:1 mappings over jackson, javascript, swift etc.

1. You have a data structure (with native datatypes). Serialize it as JSON and test it against the schema. If good, proceed.
2. Take the same data structure and serialize it as CBOR.
3. WIN

This is _not_ hard.

**Comment by bhavin-qryptal** [comment]
@jschlyter @martin-lindstrom , How do we do this validation with JSON Schema as an input without writing some additional logic to parse JSON Schema to locate all date-time and then navigating thru CBOR to check presence of Tag 0. Even https://github.com/ehn-digital-green-development/python-hcert/blob/main/tools/dgc_test.py is not performing Tag 0 check if I am not wrong.

**Comment by SchulzeStTSI** [comment]
@martin-lindstrom @jschlyter By the way, can you please send me a link to the point in the spec where this is specified: 

Timestamps (defined by JSON type string and format date-time) MUST be encoded as CBOR major type 3, a text string, and formatted per RFC 3339, section 5.6, with tag 0 as specified by RFC 8949, section 3.4.1.

I can't find the place in the hcert spec.

**Comment by jschlyter** [comment]
> I can't find the place in the hcert spec.

It is not in the hcert spec, it's in the DGC payload spec: https://github.com/ehn-digital-green-development/ehn-dgc-schema#cbor-encoding

**Comment by martin-lindstrom** [comment]
> @martin-lindstrom @jschlyter By the way, can you please send me a link to the point in the spec where this is specified:
> 
> Timestamps (defined by JSON type string and format date-time) MUST be encoded as CBOR major type 3, a text string, and formatted per RFC 3339, section 5.6, with tag 0 as specified by RFC 8949, section 3.4.1.
> 
> I can't find the place in the hcert spec.

It's actually mentioned in the implementation notes for the schema. The spec. specifies that CBOR according to the spec should be used, and https://github.com/ehn-digital-green-development/ehn-dgc-schema/blob/main/README.md clarifies this.

@jschlyter We should extend this writing with something: "Validators MUST be able to parse both tagged and un-tagged date-time strings"?

**Comment by SchulzeStTSI** [comment]
@jschlyter @martin-lindstrom @dirkx I found the changes: https://github.com/ehn-digital-green-development/ehn-dgc-schema/commit/59ed31c72f06dd4e5278da7ccd038635a3080c17#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 You did that 15 days ago and declared it as MUST. Before was there a SHOULD. This is to be honest a broken change to that what we define 4 weeks ago. Nobody sees that kind of changes in the hidden readme in the last line. Sorry, but this is not a good practise to declare a standard behaviour.

**Comment by martin-lindstrom** [comment]
> @jschlyter @martin-lindstrom @dirkx I found the changes: [ehn-digital-green-development/ehn-dgc-schema@59ed31c#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5](https://github.com/ehn-digital-green-development/ehn-dgc-schema/commit/59ed31c72f06dd4e5278da7ccd038635a3080c17#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) You did that 15 days ago and declared it as MUST. Before was there a SHOULD. This is to be honest a broken change to that what we define 4 weeks ago. Nobody sees that kind of changes in the hidden readme in the last line. Sorry, but this is not a good practise to declare a standard behaviour.

SHOULD or MUST. It really doesn't matter. What I am concerned about is that the test script complains on something that is OK. 

And furthermore, a validator app really MUST be able to handle both tagged and un-tagged date-times. 

Let's get this PR merged so that all can test against it. 

@jschlyter I suggest that MUST -> SHOULD.

**Comment by SchulzeStTSI** [comment]
@bhavin-qryptal Can you please add the tag 0 support for date time values?

**Review by SchulzeStTSI — APPROVED** [review]

**Comment by dirkx** [comment]
Eh - that was not quite the intention of that change.

The intention was good - to make sure everyone understood it *MUST* be a STRING.

So lets keep that.

**Comment by martin-lindstrom** [comment]
> Eh - that was not quite the intention of that change. The intention was good - to make sure everyone understood it *MUST* be a STRING. So lets keep that.

I referred to the MUST for tagging. That is MUST be a string cannot change.

**Comment by jschlyter** [comment]
The spec is now updated via https://github.com/ehn-digital-green-development/ehn-dgc-schema/commit/1210735c6c26c8d9073aba72dc52b95f49d4b507

**Pull request merged**
