### PR TITLE
Initial test data for Greece

### PR DESCRIPTION
**Pull request by milouk**
This PR adds initial test data on behalf of Greece

### CODE REVIEW

**Comment by milouk** [comment]
> Can you please rename "image" to "png" in the folder path?

done :)

**Comment by martin-lindstrom** [comment]
@milouk I was a little bit quick I checked your files. 

You have a bug in the CWT. Missing expiration time. See section 3.3.1 https://github.com/ehn-digital-green-development/hcert-spec/blob/main/hcert_spec.md.

**Comment by martin-lindstrom** [comment]
@milouk Now it works fine. Sweden can parse and validate your files.

**Comment by nodh** [comment]
@milouk  To me it looks like that the header in your [COSE](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/5a712fe729814ed8ce47244b8f54c50646c4a812/GR/2DCode/raw/1.json#L27) 
```
"COSE": "d28448a3012603183d0440a058f0a4061a60994685041a610fed8501624752390103a101a46376657265312e302e30636e616da462666e664d6172696f7363666e74664d4152494f5362676e684d656e656b73657363676e74684d454e454b53455363646f626a313935392d31302d3132617681aa62746769383430353339303036627670674a303742583033626d706c45552f312f32302f31353238626d616d4f52472d31303030333032313562646e01627364026264746a323032312d30312d323162636f624752626973724d696e6973747279206f66204865616c7468626369781975726e3a757663693a30313a47523a37384a3233394435233258408fd90fabf0250997814df2091c4194d5b0756aab3dd3187a1dd3045b612f69076c4b528512375cd3555e9e52fbf2a068fdd8d3c5bc7c19bd4cc76223b7ec4f20",
```
is
```
A3012603183D0440
```
which translates to
```
{1: -7, 3: 61, 4: h''}
```
and thus is missing the KID?

**Pull request merged**
