### PR TITLE
Fr add new vaccin test files

### PR DESCRIPTION
**Pull request by adelourme**
Hello
FR add 18 vaccin test files from France Health Organization (CNAM).
Thanks

### CODE REVIEW

**Comment by bhavin-qryptal** [comment]
@adelourme , Many of the new test data files have got JSON keys in lowercase. e.g. "expectedresults" instead of "EXPECTEDRESULTS" ... Please help update those files to comply with https://github.com/eu-digital-green-certificates/dgc-testdata/blob/main/README.md

**Comment by adelourme** [comment]
Hello,
Oh I 've just seen the problem thank you @bhavin-qryptal
I gonna fix the problem.
Thks

**Comment by SchulzeStTSI** [comment]
@adelourme It seems that the expiration times and the validation clocks are not correct. The check scripts throws exceptions about the expiration date.

**Comment by adelourme** [comment]
Hello, yes ok, we fix the problem. Thanks

**Comment by bhavin-qryptal** [comment]
@adelourme , There are few samples with dgc_expiry_date later than dsc_not_valid_after date. This causing tests to fail. ref: https://github.com/eu-digital-green-certificates/dgc-testdata/pull/294/checks?check_run_id=2783819470

image

**Comment by adelourme** [comment]
Hello, please could you merge this pull request. We fixed all date problems. Thanks

**Comment by daniel-eder** [comment]
@adelourme there's currently a conflict between this pr and the current main branch of this repo. Can you merge main into your branch and push? Thank you!

**Comment by adelourme** [comment]
@daniel-eder ok thanks, I gonna create new branch and pull request. Thanks

**Pull request closed without merging**
