### PR TITLE
[ES] New tests

### PR DESCRIPTION
**Pull request by Santivicen**

### CODE REVIEW

**Comment by Santivicen** [comment]
HI:
@bhavin-qryptal @SchulzeStTSI @daniel-eder  could you help me to understand what test are wrong and why? I have seen some errors, and I have remove that test from pull request, but is still block, and I don't know why.

**Comment by bhavin-qryptal** [comment]
> HI:
> @bhavin-qryptal @SchulzeStTSI @daniel-eder could you help me to understand what test are wrong and why? I have seen some errors, and I have remove that test from pull request, but is still block, and I don't know why.

[Reference](https://pipelines.actions.githubusercontent.com/yBiLiTKMF9CP11NQbrFPqkC26hqqhTLBP4zEY1ApibMPfv1GMf/_apis/pipelines/1/runs/30/signedlogcontent/3?urlExpires=2021-05-25T23%3A19%3A48.6607470Z&urlSigningMethod=HMACV1&urlSignature=uCPRsQz2PnEloRD64%2FW%2FsIvPahQKy6eHQ4ILeQHxm0c%3D)

Primarily two tests have failed.
1. test_cose_schema        : 227 Failures
2. test_expected_key_usage  : 185 Failures

Reasons:
Schema Failures:
```
2021-05-25T18:42:52.6364643Z _______________ test_cose_schema[NL/2DCode/raw/010-NL-test.json] _______________
2021-05-25T18:42:52.6365399Z tests/test_ehealth_certs.py:273: in test_cose_schema
2021-05-25T18:42:52.6366104Z     schema_validate(hcert, _get_hcert_schema())
2021-05-25T18:42:52.6367372Z /opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jsonschema/validators.py:934: in validate
2021-05-25T18:42:52.6368252Z     raise error
2021-05-25T18:42:52.6369412Z E   jsonschema.exceptions.ValidationError: '1963' does not match '(19|20)\\d{2}-\\d{2}-\\d{2}'
2021-05-25T18:42:52.6370303Z E   
2021-05-25T18:42:52.6371048Z E   Failed validating 'pattern' in schema['properties']['dob']:
2021-05-25T18:42:52.6372095Z E       {'description': 'Date of Birth of the person addressed in the DGC. ISO '
2021-05-25T18:42:52.6373072Z E                       '8601 date format restricted to range 1900-2099',
2021-05-25T18:42:52.6373781Z E        'examples': ['1979-04-14'],
2021-05-25T18:42:52.6374385Z E        'format': 'date',
2021-05-25T18:42:52.6375015Z E        'pattern': '(19|20)\\d{2}-\\d{2}-\\d{2}',
2021-05-25T18:42:52.6375658Z E        'title': 'Date of birth',
2021-05-25T18:42:52.6376252Z E        'type': 'string'}
2021-05-25T18:42:52.6376648Z E   
2021-05-25T18:42:52.6377484Z E   On instance['dob']:
2021-05-25T18:42:52.6378043Z E       '1963'
2021-05-25T18:42:52.6378824Z _____________ test_cose_schema[NL/2DCode/raw/108-NL-recovery.json] _____________
2021-05-25T18:42:52.6379604Z tests/test_ehealth_certs.py:273: in test_cose_schema
2021-05-25T18:42:52.6380406Z     schema_validate(hcert, _get_hcert_schema())
2021-05-25T18:42:52.6381528Z /opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jsonschema/validators.py:934: in validate
2021-05-25T18:42:52.6382336Z     raise error
2021-05-25T18:42:52.6383937Z E   jsonschema.exceptions.ValidationError: '1963-00' does not match '(19|20)\\d{2}-\\d{2}-\\d{2}'
2021-05-25T18:42:52.6384837Z E   
2021-05-25T18:42:52.6385585Z E   Failed validating 'pattern' in schema['properties']['dob']:
2021-05-25T18:42:52.6386631Z E       {'description': 'Date of Birth of the person addressed in the DGC. ISO '
2021-05-25T18:42:52.6387594Z E                       '8601 date format restricted to range 1900-2099',
2021-05-25T18:42:52.6388347Z E        'examples': ['1979-04-14'],
2021-05-25T18:42:52.6389051Z E        'format': 'date',
2021-05-25T18:42:52.6389701Z E        'pattern': '(19|20)\\d{2}-\\d{2}-\\d{2}',
2021-05-25T18:42:52.6390346Z E        'title': 'Date of birth',
2021-05-25T18:42:52.6390938Z E        'type': 'string'}
2021-05-25T18:42:52.6391336Z E   
2021-05-25T18:42:52.6391849Z E   On instance['dob']:
2021-05-25T18:42:52.6392393Z E       '1963-00'
2021-05-25T18:42:52.6393200Z ___________ test_cose_schema[NL/2DCode/raw/049-NL-vaccination.json] ____________
2021-05-25T18:42:52.6393997Z tests/test_ehealth_certs.py:273: in test_cose_schema
2021-05-25T18:42:52.6394685Z     schema_validate(hcert, _get_hcert_schema())
2021-05-25T18:42:52.6395889Z /opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jsonschema/validators.py:934: in validate
2021-05-25T18:42:52.6396754Z     raise error
2021-05-25T18:42:52.6397889Z E   jsonschema.exceptions.ValidationError: '1963' does not match '(19|20)\\d{2}-\\d{2}-\\d{2}'
2021-05-25T18:42:52.6398769Z E   
2021-05-25T18:42:52.6399512Z E   Failed validating 'pattern' in schema['properties']['dob']:
2021-05-25T18:42:52.6400551Z E       {'description': 'Date of Birth of the person addressed in the DGC. ISO '
2021-05-25T18:42:52.6401566Z E                       '8601 date format restricted to range 1900-2099',
2021-05-25T18:42:52.6402240Z E        'examples': ['1979-04-14'],
2021-05-25T18:42:52.6402797Z E        'format': 'date',
2021-05-25T18:42:52.6403377Z E        'pattern': '(19|20)\\d{2}-\\d{2}-\\d{2}',
2021-05-25T18:42:52.6403972Z E        'title': 'Date of birth',
2021-05-25T18:42:52.6404520Z E        'type': 'string'}
2021-05-25T18:42:52.6405072Z E   
2021-05-25T18:42:52.6405583Z E   On instance['dob']:
2021-05-25T18:42:52.6406119Z E       '1963'
2021-05-25T18:42:52.6406888Z _____________ test_cose_schema[NL/2DCode/raw/116-NL-recovery.json] _____________
2021-05-25T18:42:52.6407658Z tests/test_ehealth_certs.py:273: in test_cose_schema
2021-05-25T18:42:52.6408335Z     schema_validate(hcert, _get_hcert_schema())
2021-05-25T18:42:52.6409556Z /opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jsonschema/validators.py:934: in validate
2021-05-25T18:42:52.6410426Z     raise error
2021-05-25T18:42:52.6411654Z E   jsonschema.exceptions.ValidationError: '1963' does not match '(19|20)\\d{2}-\\d{2}-\\d{2}'
2021-05-25T18:42:52.6412478Z E   
2021-05-25T18:42:52.6413164Z E   Failed validating 'pattern' in schema['properties']['dob']:
2021-05-25T18:42:52.6414343Z E       {'description': 'Date of Birth of the person addressed in the DGC. ISO '
2021-05-25T18:42:52.6415403Z E                       '8601 date format restricted to range 1900-2099',
2021-05-25T18:42:52.6416077Z E        'examples': ['1979-04-14'],
2021-05-25T18:42:52.6416631Z E        'format': 'date',
2021-05-25T18:42:52.6417329Z E        'pattern': '(19|20)\\d{2}-\\d{2}-\\d{2}',
2021-05-25T18:42:52.6417933Z E        'title': 'Date of birth',
2021-05-25T18:42:52.6418484Z E        'type': 'string'}
2021-05-25T18:42:52.6418856Z E   
2021-05-25T18:42:52.6419334Z E   On instance['dob']:
2021-05-25T18:42:52.6420045Z E       '1963'
2021-05-25T18:42:52.6420784Z _______________ test_cose_schema[NL/2DCode/raw/018-NL-test.json] _______________
2021-05-25T18:42:52.6421522Z tests/test_ehealth_certs.py:273: in test_cose_schema
2021-05-25T18:42:52.6422199Z     schema_validate(hcert, _get_hcert_schema())
2021-05-25T18:42:52.6423421Z /opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jsonschema/validators.py:934: in validate
2021-05-25T18:42:52.6424400Z     raise error
2021-05-25T18:42:52.6425541Z E   jsonschema.exceptions.ValidationError: '1963' does not match '(19|20)\\d{2}-\\d{2}-\\d{2}'
2021-05-25T18:42:52.6426432Z E   
2021-05-25T18:42:52.6427172Z E   Failed validating 'pattern' in schema['properties']['dob']:
2021-05-25T18:42:52.6428218Z E       {'description': 'Date of Birth of the person addressed in the DGC. ISO '
2021-05-25T18:42:52.6429173Z E                       '8601 date format restricted to range 1900-2099',
2021-05-25T18:42:52.6429900Z E        'examples': ['1979-04-14'],
2021-05-25T18:42:52.6430560Z E        'format': 'date',
2021-05-25T18:42:52.6431215Z E        'pattern': '(19|20)\\d{2}-\\d{2}-\\d{2}',
2021-05-25T18:42:52.6431854Z E        'title': 'Date of birth',
2021-05-25T18:42:52.6432443Z E        'type': 'string'}
2021-05-25T18:42:52.6432839Z E   
2021-05-25T18:42:52.6433348Z E   On instance['dob']:
2021-05-25T18:42:52.6433881Z E       '1963'
2021-05-25T18:42:52.6434797Z _______ test_cose_schema[NL/2DCode/raw/258-NL-recovery+vaccination.json] _______
2021-05-25T18:42:52.6435715Z tests/test_ehealth_certs.py:273: in test_cose_schema
2021-05-25T18:42:52.6436386Z     schema_validate(hcert, _get_hcert_schema())
2021-05-25T18:42:52.6437598Z /opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jsonschema/validators.py:934: in validate
2021-05-25T18:42:52.6438451Z     raise error
2021-05-25T18:42:52.6439556Z E   jsonschema.exceptions.ValidationError: '' does not match '[A-Z]{1,10}'
2021-05-25T18:42:52.6440516Z E   
2021-05-25T18:42:52.6441376Z E   Failed validating 'pattern' in schema['properties']['r']['items']['properties']['co']:
2021-05-25T18:42:52.6442267Z E       {'description': 'Country of Vaccination / Test, ISO 3166 where '
2021-05-25T18:42:52.6442895Z E                       'possible',
2021-05-25T18:42:52.6443398Z E        'pattern': '[A-Z]{1,10}',
2021-05-25T18:42:52.6443867Z E        'type': 'string'}
2021-05-25T18:42:52.6444186Z E   
2021-05-25T18:42:52.6444774Z E   On instance['r'][0]['co']:
2021-05-25T18:42:52.6445272Z E       ''
2021-05-25T18:42:52.6446031Z __________ test_cose_schema[NL/2DCode/raw/201-NL-test+recovery.json] ___________
2021-05-25T18:42:52.6446793Z tests/test_ehealth_certs.py:273: in test_cose_schema
2021-05-25T18:42:52.6447433Z     schema_validate(hcert, _get_hcert_schema())
2021-05-25T18:42:52.6448544Z /opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jsonschema/validators.py:934: in validate
2021-05-25T18:42:52.6449345Z     raise error
2021-05-25T18:42:52.6450359Z E   jsonschema.exceptions.ValidationError: '' does not match '[A-Z]{1,10}'
2021-05-25T18:42:52.6451162Z E   
2021-05-25T18:42:52.6452157Z E   Failed validating 'pattern' in schema['properties']['t']['items']['properties']['co']:
2021-05-25T18:42:52.6453256Z E       {'description': 'Country of Vaccination / Test, ISO 3166 where '
2021-05-25T18:42:52.6454048Z E                       'possible',
2021-05-25T18:42:52.6454658Z E        'pattern': '[A-Z]{1,10}',
2021-05-25T18:42:52.6455251Z E        'type': 'string'}
2021-05-25T18:42:52.6455633Z E   
2021-05-25T18:42:52.6456175Z E   On instance['t'][0]['co']:
2021-05-25T18:42:52.6456689Z E       ''
2021-05-25T18:42:52.6457612Z ___________ test_cose_schema[NL/2DCode/raw/078-NL-vaccination.json] ____________
2021-05-25T18:42:52.6458396Z tests/test_ehealth_certs.py:273: in test_cose_schema
2021-05-25T18:42:52.6459089Z     schema_validate(hcert, _get_hcert_schema())
2021-05-25T18:42:52.6460288Z /opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jsonschema/validators.py:934: in validate
2021-05-25T18:42:52.6461156Z     raise error
2021-05-25T18:42:52.6462097Z E   jsonschema.exceptions.ValidationError: 0 is less than the minimum of 1
2021-05-25T18:42:52.6463076Z E   
2021-05-25T18:42:52.6463884Z E   Failed validating 'minimum' in schema['properties']['v']['items']['properties']['sd']:
2021-05-25T18:42:52.6465124Z E       {'description': 'Dose Number / Total doses in Series: positive '
2021-05-25T18:42:52.6465966Z E                       'integer, range: [1,9]',
2021-05-25T18:42:52.6466661Z E        'maximum': 9,
2021-05-25T18:42:52.6467214Z E        'minimum': 1,
2021-05-25T18:42:52.6467779Z E        'type': 'integer'}
2021-05-25T18:42:52.6468186Z E   
2021-05-25T18:42:52.6468717Z E   On instance['v'][1]['sd']:
2021-05-25T18:42:52.6469130Z E       0
2021-05-25T18:42:52.6470132Z ____ test_cose_schema[NL/2DCode/raw/288-NL-test+recovery+vaccination.json] _____
2021-05-25T18:42:52.6471104Z tests/test_ehealth_certs.py:273: in test_cose_schema
2021-05-25T18:42:52.6471799Z     schema_validate(hcert, _get_hcert_schema())
2021-05-25T18:42:52.6473068Z /opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/jsonschema/validators.py:934: in validate
2021-05-25T18:42:52.6473939Z     raise error
2021-05-25T18:42:52.6475032Z E   jsonschema.exceptions.ValidationError: '' does not match '[A-Z]{1,10}'
2021-05-25T18:42:52.6475898Z E   
2021-05-25T18:42:52.6476752Z E   Failed validating 'pattern' in schema['properties']['t']['items']['properties']['co']:
2021-05-25T18:42:52.6477851Z E       {'description': 'Country of Vaccination / Test, ISO 3166 where '
2021-05-25T18:42:52.6478751Z E                       'possible',
2021-05-25T18:42:52.6479317Z E        'pattern': '[A-Z]{1,10}',
2021-05-25T18:42:52.6479870Z E        'type': 'string'}
2021-05-25T18:42:52.6480225Z E   
2021-05-25T18:42:52.6480730Z E   On instance['t'][1]['co']:
2021-05-25T18:42:52.6481209Z E       ''
2021-05-25T18:42:52.6481903Z _______________ test_cose_schema[NL/2DCode/raw/025-NL-test.json] _______________
```
Key Usage Failures:
Reason: AssertionError: DGC adheres to schema but contains multiple certificates of different types. @SchulzeStTSI and @daniel-eder , Please confirm if this is a valid error OR not a valid error. As I have tried to confirm this [here](https://github.com/eu-digital-green-certificates/dgc-testdata/issues/161) , but have not recd confirm response. Also, please let me know if test logic needs to be updated.

**Comment by bhavin-qryptal** [comment]
> HI:
> @bhavin-qryptal @SchulzeStTSI @daniel-eder could you help me to understand what test are wrong and why? I have seen some errors, and I have remove that test from pull request, but is still block, and I don't know why.

@Santivicen @SchulzeStTSI @daniel-eder 
All these failures are related to NL files. We need to re-open ONE or BOTH of 
https://github.com/eu-digital-green-certificates/dgc-testdata/issues/146
https://github.com/eu-digital-green-certificates/dgc-testdata/issues/107

And also re-introduce NL entry in known issue list.

**Comment by daniel-eder** [comment]
@bhavin-qryptal that is odd, after we merged the NL PR and removed them from the known list the tests ran through without issue. Looks like we missed something. I'll revert & reopen then.

**Review by daniel-eder — APPROVED** [review]

**Pull request merged**
