### PR TITLE
Test files from AT

### PR DESCRIPTION
**Pull request by nodh**
Import four test files from AT

### CODE REVIEW

**Review by SchulzeStTSI — APPROVED** [review]

**Comment by martin-lindstrom** [comment]
It seems like you add the entire HCERT and not just the DGC payload in the CBOR-element.

```
{4: 1620237600, 6: 1620064800, 1: "AT", -260: {1: {"v": [{"dn": 1, "ma": "ORG-100030215", "vp": "1119305005", "dt": "2021-02-18", "co": "AT", "ci": "urn:uvci:01:AT:10807843F94AEE0EE5093FBC254BD813P", "mp": "EU/1/20/1528", "is": "BMSGPK Austria", "sd": 2, "tg": "840539006"}], "nam": {"fnt": "MUSTERFRAU<GOESSINGER", "fn": "Musterfrau-G\u00f6\u00dfinger", "gnt": "GABRIELE", "gn": "Gabriele"}, "ver": "1.0.0", "dob": "1998-02-26"}}}
```

SE, BG and RO adds just the DGC payload.

**Comment by martin-lindstrom** [comment]
@SchulzeStTSI I have attempted to point out the the test instructions need to be more clear about each field.

**Comment by martin-lindstrom** [comment]
@SchulzeStTSI @nodh But I see that the files in common and the example in README also includes all fields from the CWT. So SE, RO and BG may be wrong. Anyway. Please be clear regarding the instructions.

**Comment by NamingException** [comment]
In the readme it says at test 2 "Create CBOR from JSON Object. Validate against the CBOR content in the RAW File. See note 2 below." so the CBOR of the json and not the entire HCERT might also apply.

**Pull request merged**
