### PR TITLE
Added new jason files for PCR test and rapid test

### PR DESCRIPTION
**Pull request by kristinaleko**

### CODE REVIEW

**Comment by daniel-eder** [comment]
@kristinaleko Thank you for the update - can you look into the conflicts it found and resolve them before we merge the PR?

**Comment by kristinaleko** [comment]
@daniel-eder probably i have made some changes in the mail section and now on my fork. The data on my fork are all correct and should be tranfered to the main, if you can assist how to resolve this conflicts i woould be gratefull?

**Comment by daniel-eder** [comment]
@kristinaleko thank you for the confirmation, I merged it for you, using the version of the files in your fork

**Comment by kristinaleko** [comment]
@daniel-eder thanx

**Pull request merged**
