### PR TITLE
danish test sets

### PR DESCRIPTION
**Pull request by jvitrifork**

### CODE REVIEW

**Comment by SchulzeStTSI** [comment]
@martin-lindstrom are empty r, v or t sections allowed in the payload according to the hCert Spec, if one of the others is filled? I guess the schema requires then the mandatory fields of each section if opened right?

**Comment by jvitrifork** [comment]
Sure - the statements are generated using a morphed version of https://github.com/DIGGSweden/dgc-java/blob/1f39749bac2b3394d1d131d39607008efb1adc49/create-validate/src/test/java/se/digg/dgc/interop/CreateTestDataTest.java#L270. I believe that the empty arrays can be removed from the JSON content; The CBOR content stays the same - meaning that the empty sections are not present in the actual payload, and merely artifacts from a not-properly initialized json serialization as @martin-lindstrom points out.

**Comment by jvitrifork** [comment]
So ... should I remove the unwanted artifacts in the json payload as it is merely unwanted noise, and framework implementation specific?

**Review by SchulzeStTSI — APPROVED** [review]

**Comment by martin-lindstrom** [comment]
> Sure - the statements are generated using a morphed version of https://github.com/DIGGSweden/dgc-java/blob/1f39749bac2b3394d1d131d39607008efb1adc49/create-validate/src/test/java/se/digg/dgc/interop/CreateTestDataTest.java#L270. I believe that the empty arrays can be removed from the JSON content; The CBOR content stays the same - meaning that the empty sections are not present in the actual payload, and merely artifacts from a not-properly initialized json serialization as @martin-lindstrom points out.

That's not true. The empy arrays are there in the CBOR-encoding as well:

```
{"ver": "1.0.0", "nam": {"fn": "Klaus", "fnt": "KLAUS", "gn": "J\u00f8rgensen", "gnt": "JOERGENSEN"}, "dob": "1983-01-06", "v": [{"tg": "840539006", "vp": "1119349007", "mp": "EU/1/20/1528", "ma": "ORG-100030215", "dn": 2, "sd": 2, "dt": "2021-04-13", "co": "DK", "is": "Danish Health Data Authority", "ci": "urn:uuid:1c11e5a6-8008-4cf2-8e67-d5dac166e67a"}], "t": [], "r": []}
```

**Comment by jvitrifork** [comment]
Got it ... thx

**Comment by martin-lindstrom** [comment]
> Thats definitely a bug

Yes. If you are using the CBOR extension to FasterXML, the fix is:

```
mapper.setSerializationInclusion(Include.NON_NULL);
mapper.setSerializationInclusion(Include.NON_EMPTY);
```

**Comment by jvitrifork** [comment]
I'm mostly using your code @martin-lindstrom -  but I'm a few versions behind, as I currently still have to backport it ... so at least I know how to fix it ;)

**Comment by nodh** [comment]
@jvitrifork I see that your `2.json` contains a Test entry, but `tc` is missing. Shouldn't this be required, according to the [Spec](https://github.com/ehn-digital-green-development/ehn-dgc-schema/blob/58605fffbe48a7cf77f55d2ce535cd1c4b167cd3/DGC.combined-schema.json#L198)?

**Comment by jvitrifork** [comment]
@nodh @martin-lindstrom @aspergerianer @SchulzeStTSI issues should be fixed with https://github.com/eu-digital-green-certificates/dgc-testdata/pull/49

**Pull request merged**
