### PR TITLE
Fixing standardized names (#220)

### PR DESCRIPTION
**Pull request by jozemlakar**
1.0.0 of the json schema provides the following regex https://github.com/eu-digital-green-certificates/ehn-dgc-schema/blob/02bf437b1f2efe80982e3172a85a757e549b3c64/DGC.combined-schema.json#L95

Note that this field is the standardized family name, for the original name you can use https://github.com/eu-digital-green-certificates/ehn-dgc-schema/blob/02bf437b1f2efe80982e3172a85a757e549b3c64/DGC.combined-schema.json#L86

### CODE REVIEW

**Review by daniel-eder — DISMISSED** [review]

**Comment by daniel-eder** [comment]
@jozemlakar I did not look into it further yet, but it seems the files still fail (albeit now xfail because #220 is marked as known issue). Can you look at the test result html linked in the (passed due to xfail) data verification? If you need further assistance please ping and I'll review as well

**Comment by jozemlakar** [comment]
We made a mistake while merging. Should be fixed now.

**Comment by jozemlakar** [comment]
@daniel-eder from what we see in the logs, this should be good. No more XFailed on our samples.

**Review by daniel-eder — APPROVED** [review]

**Comment by daniel-eder** [comment]
@jozemlakar many thanks!

**Pull request merged**
