### PR TITLE
SI: Adding test and recovery samples and changing vac samples to one entry

### PR DESCRIPTION
**Pull request by jozemlakar**

### CODE REVIEW

**Comment by jozemlakar** [comment]
Hm, weird errors. As if it was not possible to get files from GitHub.

**Review by SchulzeStTSI — CHANGES_REQUESTED** [review]
@jozemlakar    In file 5 is the prefix not able to decode here: https://github.pathcheck.org/debug.html can you check that?

**Comment by daniel-eder** [comment]
@jozemlakar due to a change in how the EHNs JSON schema URL works, the check for your PR currently fails. Could you update your branch to the latest main to incorporate the updated and working schema URL (specifically, the test script with said updated url)? Then we can see if there are any actual issues left. 

Thanks!

**Comment by jozemlakar** [comment]
@daniel-eder we have merged the main and that fixed the URL error. However now we have a problem with sc field (too large of precision in sc field). Will have to wait on Monday.

**Comment by jozemlakar** [comment]
Failure is due to https://github.com/DIGGSweden/dgc-java/issues/66

**Comment by martin-lindstrom** [comment]
@daniel-eder @SchulzeStTSI Why is a fine grained time a problem? It is unnecessary, yes, but still. By washing away these odd cases from the test files you actually give validators less data to parse. In my meaning, this shouldn't be an error.

**Comment by jozemlakar** [comment]
@martin-lindstrom while I would agree, there is also the issue of validation apps that are failing on this. So if we say, we allow fine grained time, then we are also braking verifier apps. One of those "we are right, but at what price" things.

**Comment by martin-lindstrom** [comment]
> @martin-lindstrom while I would agree, there is also the issue of validation apps that are failing on this. So if we say, we allow fine grained time, then we are also braking verifier apps. One of those "we are right, but at what price" things.

One could argue that those validator apps should be interested in fixing the problem on their side instead of attempting to get all issuers to limit what is created...

**Comment by martin-lindstrom** [comment]
@daniel-eder @SchulzeStTSI About date-time...

From the [specification](https://teams.microsoft.com/l/file/d6c6f943-6ad3-433b-b12b-2cc61fca4ee0?tenantId=b24c8b06-522c-46fe-9080-70926f8dddb1&fileType=docx&objectUrl=https%3A%2F%2Feceuropaeu.sharepoint.com%2Fteams%2FGRP-eHNTechIOPSG%2FShared%2520Documents%2FGeneral%2FOngoing%2520work%2FJSON%2520Schema%2FJSON%2520Schema%2520Specification-v1.2.1.docx&baseUrl=https%3A%2F%2Feceuropaeu.sharepoint.com%2Fteams%2FGRP-eHNTechIOPSG&serviceName=aggregatefiles):

The date and time when the test sample was collected. The time MUST include information on the time zone. The value MUST NOT denote the time when the test result was produced.

Exactly 1 (one) non-empty field MUST be provided.

One of the following ISO 8601 formats MUST be used. Other options are not supported.

```
YYYY-MM-DDThh:mm:ssZ 
YYYY-MM-DDThh:mm:ss[+-]hh 
YYYY-MM-DDThh:mm:ss[+-]hhmm 
YYYY-MM-DDThh:mm:ss[+-]hh:mm 
```

Examples:

```
"sc": "2021-08-20T10:03:12Z"	(UTC time) 
"sc": "2021-08-20T12:03:12+02"	(CEST time) 
"sc": "2021-08-20T12:03:12+0200"	(CEST time) 
"sc": "2021-08-20T12:03:12+02:00"	(CEST time) 
```
I heard from @jozemlakar that you expect fractions and don't accept the above? Is that correct? If so, the test scripts need to be updated.

**Comment by jozemlakar** [comment]
@daniel-eder @SchulzeStTSI @martin-lindstrom this is base on failed checks when I submitted samples without fractions. Checks failed because expected value was
'sc', '2021-06-07T16:51:35.000000Z'
our value was
'sc', '2021-06-07T16:51:35Z'

**Review by SchulzeStTSI — APPROVED** [review]

**Pull request merged**
