### PR TITLE
new test data for Greece

### PR DESCRIPTION
**Pull request by louridas**

### CODE REVIEW

**Comment by daniel-eder** [comment]
@louridas the automated test suite found a few issues with the changes in this PR. Can you take a look at the report it generated?
https://github.com/eu-digital-green-certificates/dgc-testdata/suites/2822888838/artifacts/62871681 

@bhavin-qryptal can you take a look at the output as well? I didn't yet have time to properly look into the test suite, and I'm not entirely certain what the output in this case means - maybe you can add some clarification?

Thank you both!

**Comment by bhavin-qryptal** [comment]
Easiest option would be to visit Test Run Summary (https://github.com/eu-digital-green-certificates/dgc-testdata/actions/runs/874261798) and click on the Artifacts link (https://github.com/eu-digital-green-certificates/dgc-testdata/suites/2822888838/artifacts/62871681)

Following that, I have got, which suggests that something is wrong with 2DCODE field for GR/2DCode/raw/1.json also (2.json, 3.json and 4.json).


image

**Comment by louridas** [comment]
I understand that the error is that config_env[QR_CODE] is None, so it
fails.

However, QR_CODE is not supposed to be set in the test data JSON file as
specified in: https://github.com/eu-digital-green-certificates/dgc-testdata.

Am I missing something?

**Comment by bhavin-qryptal** [comment]
Looking bit more at this, it seems that 2DCODE field value is having extra spaces in that.

**Comment by daniel-eder** [comment]
> I understand that the error is that config_env[QR_CODE] is None, so it fails. However, QR_CODE is not supposed to be set in the test data JSON file as specified in: https://github.com/eu-digital-green-certificates/dgc-testdata. Am I missing something?
@SchulzeStTSI can you weigh in on this?

**Comment by bhavin-qryptal** [comment]
1. QR_CODE ==> '2DCODE'
2. '2DCODE' value is not a valid base64 string. You could see quite a many spaces there.

**Comment by bhavin-qryptal** [comment]
@daniel-eder , I have made minor changes in the test script to have better reporting in case of such failures going forward. Ref https://github.com/eu-digital-green-certificates/dgc-testdata/pull/203

**Comment by louridas** [comment]
I do not see any spaces in 2DCODE. There are spaces in PREFIX, which
is base45 encoding, and spaces are valid in base45, or are you
referring to something else?

**Comment by bhavin-qryptal** [comment]
> I do not see any spaces in 2DCODE. There are spaces in PREFIX, which is base45 encoding, and spaces are valid in base45, or are you referring to something else?
> […](#)
> On Tue, May 25, 2021 at 12:46 PM Bhavin Sanghvi ***@***.***> wrote: QR_CODE ==> '2DCODE' '2DCODE' value is not a valid base64 string. You could see quite a many spaces there. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

I am referring to 2DCODE. It seems to be invalid base64 value. May be I made an error in saying that it contains space. However, I am unable to convert 2DCODE into image. I have tried using https://www.base64decode.net/base64-image-decoder for the same.

**Comment by bhavin-qryptal** [comment]
@louridas , For example I have derived valid base64 value for 2DCODE for 1.json file using https://www.base64-image.de/
====

iVBORw0KGgoAAAANSUhEUgAAAXQAAAF0AQAAAAAbGP/+AAAFwklEQVR4nO2bTW40NxJEXxuzj7qB738s3+D1CWIWwZK9m/EMYHDxtSBIkLjIYiUz4yf5KX/n8/3tby2HX+t/rb98/efzeT5fPp8vz+f58OX5fr/AF77P98Pz5Xmez+fz3Bc/bdo0YpMmNrGtRlQohC3zxvhJJGATJFqkaBUwJQ25N/7WpkYjYMt2PJJgvTt+iJEQIFiT7T2txJv3vw1LnUKaQttzHPYrXpr/n/KB/BcrvxCv67/0z0+qTQOJraRYgiRbct3+0wpUJLQFGkkFSLPilJob82chlyYiNNlRbmvVpECIXnp+6yk8jSRGyymdRrWCa2oXxm8iLS0JtNY2uMbc2pWiS+OHHc/TA+w229YsuRDttfkzzLNAoyBAkQOMwBpz5/5XQ6wVA5iE1pYI+6uWO/c/oQ0MpGEotkNvQkpSxTv3P00MNiZZEUrSats4VNfk0vxPIqUmhFjQsKMxVJrVozvjLw2SF0FYaWogltKYtLfiT42py/6YUmOj6Y5u6Mr/lfEHQklp0daTR9FGgli5Ej/v/DrM6dgjZSciuKacBLi0frYgGWsfGVY7Apal0WFot8bfcVwSuzrvoZGUDj5fmz9NmPzQGlvWhkuHPqNtvDZ/RAuUNv7k0OKG2HWBS+sPShWqJWpD29q20x6Ucmn8dYTLqk1LyR4C9zrGIC+Nfz9YBQpEB5sF8lNG4dLzm58vw7pw3Vs4qIcBOy7c/9/gC8/3ge/z+x/KQ/N9+PAtDzx/QPDLQ/6ZeP7ep/WQ23BUkhBpYrr0mfZ2b/4scGsdC2aQCA4fBu7tv0gPSSEZYxn0t0PVGbu5tH+ZAjZ0NsDhwjEoJi8wvTD+fwF8BSDPl2+fh3zi0weSJ/mD33n6ffwn4vnf+tesC5fs9RxcU8NYcLz2/DrKC8fFCG8qBekowc3+xctuRwES3TOslja1SbhWfzYedarMdGxwWTT9ZNzs1v3npVcDCZkKcTyBZhbq5NAr4+9L4k1aGVdBXlQ6MHdr/ryyVc8BJrp2TObMjCPcqh9SPWfXk+YJM4GX96cF39p/zWTDZlo0lO340VROW7iVv6TmKDzHuOhr/HrsyAa9Nf8pSSY9jAJvloO0dd72xfxxZsWwP1Np54OFns5bczzhC+MX05WbMA6QzIWpDFB0xfTK+DPG4jyXQN/WVUsmqYRr+fscyNbgT7AFEwRmI/Xe+LfjBkP6TqLMVtq/Z6bemj9hhL0OOcQDi2AYdL9e6183mxd7Z35OqXGvgPka6a3+HSbxHdMYdNh39ijzHnMv/slcurTHRrJ7lFmqcETcO/d/5QfBM/+W6YhOC2Xl6Fr9px7pB9e87PFQpfZPR+PS/JfVd5mUuKmlY6D64jev9d+Hm4/AkI2MrQevl5kzhXtp/FN5SPPavQM7HOt3rcER4wvjf9VPMBFjWQa1nEk+zxDxjfG79rWSybEwtOX1NXqG+W6N/8c57Q9qdsrPYk9qr+XvMWxab9ZFm6yjbWqGnnmCi/O/umKfd2hjsC2Eedi5Fr81U35o5mIM729wdepE4736yTErXImMm0KM5cydK7nYfzl+0RnUXpnhx5IZMk0vnj+Ujv72GNVnfCnztLPDza36Q2ya6eVjAvMBQHPI5Waw7owfs2yfFrGrSHX05WhwXo3fwDKSdTzT+dftdCEzdH1n/JNJhpZhXGATNVNOTi3i1vmloZ6DEH6kH7ObVNQzAXorfvCUfuGg/DHgc/nCtQPsrfrPkRBj4mp9yWbKNridmQGXxn+mxHT3SHpmCKYFFdue6dxL8x9yBnBn9Br0dK/Bu5XPS+v/K3nKKPBpA5C9C/YE1+5/3sk3Wbw/l2A2/tZXlbv0/shoYw5gMN08gbt/Z1pfPfra+BM6lz31CNEZAdvNto3y3Rl/z7xqJzg05zbSO3g1/by5NH84ikNhJukA3DHDJi4yb+m++D/9z2v+8rnu/uyv9b/W/z/r/w0VNsyoKnkA5wAAAABJRU5ErkJggg==

**Comment by louridas** [comment]
I think I can see the difference.

There are various base64 dialects. In your example, for instance, you use
'+', while we use '-'.

In particular, our dialect is
https://datatracker.ietf.org/doc/html/rfc4648#section-5, which is called
the URL and filename safe version of the standard.

The reason why we started using *this* dialect, is that this is the dialect
that must be used for the kid. So apparently it seems that we have to use
two different base64 dialects: the URL-friendly one for the kid, and the
"traditional" one for the QR code.

**Comment by daniel-eder** [comment]
@bhavin-qryptal thanks for helping with the verification, @louridas thanks for updating the data, it looks good now :)

**Review by daniel-eder — APPROVED** [review]

**Pull request merged**
