### PR TITLE
Fixed pull issues

### PR DESCRIPTION
**Pull request by ava3a13**

### CODE REVIEW

**Comment by ava3a13** [comment]
@daniel-eder Hello Daniel! Can you review our commit? Thank you in advance!

**Comment by daniel-eder** [comment]
@ava3a13 can you check out the log for the failed check above? Seems something is not right

**Comment by ava3a13** [comment]
> @ava3a13 can you check out the log for the failed check above? Seems something is not right

As I see in logs none of the 'GE' data has failed test pass. Should I have done something otherwise?

**Comment by ava3a13** [comment]
@daniel-eder Running tests locally on clean repository (Without adding our files), still outputs the same amount of errors. 
cmd_ck30SnlEB0

And after the addition of files: 
cmd_wRY5ssydzb

**Comment by daniel-eder** [comment]
@ava3a13 apologies! Seems there are problems with the data from FI that were not yet marked as known issues.
Can you update your fork to the latest commit on the dgc-testdata main branch (it contains the updated issue list and now successfully passes the tests, see https://github.com/eu-digital-green-certificates/dgc-testdata/actions/runs/1294458321) so I can re-run the test?

**Review by daniel-eder — APPROVED** [review]

**Comment by daniel-eder** [comment]
@ava3a13 thanks a lot, tests confirmed now!

**Comment by ava3a13** [comment]
@daniel-eder  Thank you!

**Pull request merged**
