### PR TITLE
IE

### PR DESCRIPTION
**Pull request by Eamon-Coyne-Ireland**
Irish EU Digital COVID Certificate Test Data

### CODE REVIEW

**Review by SchulzeStTSI — CHANGES_REQUESTED** [review]
@Eamon-Coyne-Ireland i can't decode the PREFIX and BASE45 value. There are spaces in it. Do you use a proper base45 decoding?

**Comment by Eamon-Coyne-Ireland** [comment]
Dear Stefan,

Thanks for the prompt reply..

We took it stpaces are allowed in the charset for Base45 is "
*0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ $%*+-./:*" See below.


Is this not the case?


Thanks,

Eamon.




Java:

https://github.com/ehn-digital-green-development/base45-java/blob/master/src/main/java/nl/minvws/encoding/Base45.java

private static final byte[] toBase45 = {

        '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C',

        'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',

        'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', *' '*, '$', '%',

        '*', '+', '-', '.', '/', ':'

};



PHP:

https://github.com/ehn-digital-green-development/base45-php/blob/main/base45.php

$charset = "*0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ $%*+-./:*";



JavaScript:

https://github.com/ehn-digital-green-development/base45-js/blob/main/lib/base45-js.js

const encoding = ["0", "1", "2", "3", "4", "5", "6", "7", "8", "9",

        "A", "B", "C", "D", "E", "F", "G", "H", "I", "J",

        "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T",

        "U", "V", "W", "X", "Y", "Z", *" "*, "$", "%", "*",

        "+", "-", ".", "/", ":"];



Swift:

https://github.com/ehn-digital-green-development/base45-swift/blob/main/Sources/base45-swift/Base45.swift

let BASE45_CHARSET = "*0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ $%*+-./:*"



C#:

https://github.com/ehn-digital-green-development/base45-cs/blob/master/Base45/Base45Encoding.cs

private static readonly char[] _Encoding = {'0', '1', '2', '3', '4', '5',
'6', '7', '8', '9',

                                        'A', 'B', 'C', 'D', 'E', 'F', 'G',
'H', 'I', 'J',

                                        'K', 'L', 'M', 'N', 'O', 'P', 'Q',
'R', 'S', 'T',

                                        'U', 'V', 'W', 'X', 'Y', 'Z', *' '*,
'$', '%', '*',

                                        '+', '-', '.', '/', ':' };



C:

https://github.com/ehn-digital-green-development/base45-ansi-C/blob/main/base45.c

static char _C2I[256] = {//...



*Eamon Coyne*
Aikikai Ireland President

Mail: ***@***.***
Tel: +353876693711
Skype: eamon.coyne
Web: www.AikikaiIreland.ie

**Comment by Eamon-Coyne-Ireland** [comment]
Good morning Stefan,

Any further information on below?.

Thanks in advance,
Eamon/

*Eamon Coyne*
Aikikai Ireland President

Mail: ***@***.***
Tel: +353876693711
Skype: eamon.coyne
Web: www.AikikaiIreland.ie

**Comment by SchulzeStTSI** [comment]
@Eamon-Coyne-Ireland I Think the base45 is okay. But the content which you encode is wrong.  The debugger outputs: "oV8jX4OXsDqufIUTWlQj7okctn7aD/kpRgYSEWg5PQIt9D/gKCfIZvYSNJcPjgPFFnDZwwFYCDv2+Ep1QES86q48Lo88T2bPpV50U4vWAnziSQkpIoktfUPpMDAngSCX5CQlfD2Zz0U3yb8Io8Vlt/uCyRv9FwqsrmHMUI49wPdVUX8hGu+JO4FnCJIDGiiBJX/usE4azJwE7VJwflQi1y0yNsGhAiTtT14K9gTT72YnAOFqD4MUW/phnSVs3UrXW1MtChOXaKSDIvdSHcU4FywFaAwcFCQiThE4ppRyYBsgSDnVBU1mAtH0NzzVIkUkFDDclEyXIPA+0KUKT2A0+O1mRhfYiUc0RE+cjVgzxNEDbWdHZAkmBVjx+k5mV8EEYuEHkApAE7BAetbTKLYySL/OjkBcPtvwYdjsNkiRM+ilMRlKdz4l3CiNTBlSAcAf9Zs6Q1bmB4F2bZr8EOmq+Rpds6UwaDl+cag0mDBTAwyjhoaaBdjy" instead of a CBOR COSE structure. Did you anywhere a mistake in the encoding?

**Comment by SchulzeStTSI** [comment]
@Eamon-Coyne-Ireland 

Try this url here:

https://github.pathcheck.org/debug.html

with the examples:

Your PREFIX:

HC1:7PI+D5-%U9RM3JIFMQ00JQWI+A4*4IE%JY:0/U./*-0AHCB -J2VQSZO%TJHG-+ZJKS 59$.9V+D+W8QDL62O5:%7T$*C 5U3BKK0OF07.9J:J%DFY*VTA8PGIQ3TV V-Y9F3M0*LV$GW0 : U-Y2NCJMUJBS6SSN%ICVI1/:3W$ 1P:+*EX3YGQ63G1N49W-RLFN-AQAH5+94774FZMYGKA1CQ 8OJ:WSY/$NHV*EM/RLELHHQKYK5KH7PEXPL.1US7H $BW7::JGOSVZ$$I*30WN7A-CI%+XMOK1AJ-0NH%Q78:/ -T%Z$ 1GL H+BC8X1G+Z+L6+AJ46$N%HEDJ**B*4O85RDGGXAC7FLU4:$H.SA-V9 2-05Y*XIU.F2CN68VPX$:7+BNX7FLFT%9I7687EF+0BU-QU: PYTIY1IY2+7GR5AJG7HI AO..BLW6ZV7$T2AGWQ9Z:/DN3S+S-0UT.*NSFFJ+0YW:52M.ULKLK27LR8*HF+BSH$Q/%LUX%J4JCZ2%A/VP+MZGY573AQ9EA-W6CXPSGD0E00NS/0T34AAN+EKE-ATL6R/4HQXT3*7BZUPES:8F.OEIW-P/-Z$76GX5K+52.AG40


SE PREFIX:

HC1:NCFOXN%TSMAHN-HVN8J7UQMJ4/3RZLH62V2G1PC9CMSRH+QKFNTAVD3B19*AJCBMF6.UCOMIN6R%E5BD7HG8CU6O8QGU68ORJSPAEQOIR+SPCVO.28DDQHQ1BW9XX7ZY7NTICZU1*8X/KQ96/-KKTCY73JC3KD3LWT HB3ZC64JX7JQ1LK$2965VMFD-48YI 3533LC4TZ0BR/S09T./0ZYTS P-$0R:67PPDFPVX1R270:6C$Q0R6EOMUF5LDCPF5RBQ746B46O1N646RM9AL5CBVW566LH 469/9-3AKI6%T6LEQ-P6UQK*%NH$RSC9FFFW+7H9N$W2JO2C6S3UJ92KEST.ZJ-8B ZJ83B 2TAAUZZ2LH2%EUBUJZ0KZPIR145%T0YIF0JEYI1DLNCK1627ACW-T%NSY18KT911GL.EHNTI+SB-5A-ARUQNFW$ 2:.NU6W/CU8WDTFVG:BG3JFCSAVH-4V:HP4$0/.D9OV-RM60R7Z3B8PXICK+L/S1P*O:FG


Do you see the difference? I looks for like that the content of the base45 is encoded in base64. But not everywhere just in some of the codes.

**Comment by Eamon-Coyne-Ireland** [comment]
Dear Stefan.

Thanks for much for the additional information, we will check it out.

Also can you give me the details for the acceptance gateway URL please?.

Thanks,
Eamon,

*Eamon Coyne*
Aikikai Ireland President

Mail: ***@***.***
Tel: +353876693711
Skype: eamon.coyne
Web: www.AikikaiIreland.ie

**Review by SchulzeStTSI — APPROVED** [review]

**Review by SchulzeStTSI — APPROVED** [review]

**Comment by daniel-eder** [comment]
@Eamon-Coyne-Ireland due to a change in how the EHNs JSON schema URL works, the check for your PR currently fails. Could you update your branch to the latest main to incorporate the updated and working schema URL? Then we can see if there are any actual issues left. 

Thanks!

**Comment by Eamon-Coyne-Ireland** [comment]
Dear Daniel,

We will look into it and get back to you.

Many thanks for the mail,

@Nenad/@Nikos do you need any further information from Daniel?.

Kind regards,
Eamon,

*Eamon Coyne*
Aikikai Ireland President

Mail: ***@***.***
Tel: +353876693711
Skype: eamon.coyne
Web: www.AikikaiIreland.ie

**Comment by Eamon-Coyne-Ireland** [comment]
Dear Daniel, all,

We have made changes and committed the new files to the IE branch,
Let us know if you need anything further, keen to have the IE branch
available on the "main" branch.

Kind regards,
Eamon.

*Eamon Coyne*
Aikikai Ireland President

Mail: ***@***.***
Tel: +353876693711
Skype: eamon.coyne
Web: www.AikikaiIreland.ie

**Comment by Eamon-Coyne-Ireland** [comment]
Thanks :-)

*Eamon Coyne*
Aikikai Ireland President

Mail: ***@***.***
Tel: +353876693711
Skype: eamon.coyne
Web: www.AikikaiIreland.ie

**Pull request merged**
