### PR TITLE
SK test data contribution

### PR DESCRIPTION
**Pull request by rho-sk**

### CODE REVIEW

**Comment by daniel-eder** [comment]
Reopened to force automated tests to run.

**Comment by daniel-eder** [comment]
@rho-sk it seems your PR is introducing some new validation issues. Attached is the workflow result as filterable HTML: 
[dgc_testdata_report.zip](https://github.com/eu-digital-green-certificates/dgc-testdata/files/6536865/dgc_testdata_report.zip)

Can you take a look? 
Thanks!

**Comment by rho-sk** [comment]
Issues are fixed

**Review by daniel-eder — APPROVED** [review]

**Comment by rho-sk** [comment]
> > Issues are fixed
> 
> Fantastic, looks good now, thank you!

Thank you too, i adopted your automatic tests into our project, to verify every build.

**Pull request merged**
