### PR TITLE
Added test data for Norway

### PR DESCRIPTION
**Pull request by florinpnhn**
- 1: Vaccination - OK

-  2: Recovery - OK

- 3: Test - OK

### CODE REVIEW

**Review by oddahl — APPROVED** [review]
👍

**Comment by martin-lindstrom** [comment]
From a visual inspection: 

1.json contains 5 vaccination entries. Is this really what you want?

UVCI is missing prefix `URN:UVCI`. See https://github.com/ehn-dcc-development/ehn-dcc-schema/wiki/FAQ#prefix.

2.json: `tg` is set to `null`. It is a required field so it won't pass a schema validation.

And `null` should never be used (even for optional attributes).

3.json: `tg` and `tc` is `null`. Prefix of UVCI is there but it should be in uppercase.

**Review by martin-lindstrom — CHANGES_REQUESTED** [review]
Se my previous comments...

**Comment by florinpnhn** [comment]
> Se my previous comments...

@martin-lindstrom Can you review changes? We have updated to v 1.3.

**Comment by martin-lindstrom** [comment]
For the 3.json file I see that you have included the `ma` field. This field MUST NOT appear in a NAAT-test certificate.

In the same file you also specify `dr` which is no longer part of the schema. It also holds a funny date.

**Pull request closed without merging**
