### PR TITLE
SI: All new codes schema 1.3.0 from NB (ACC)

### PR DESCRIPTION
**Pull request by jozemlakar**

### CODE REVIEW

**Comment by jozemlakar** [comment]
Looks like it is failing on ES codes and not on codes I sent.

**Comment by daniel-eder** [comment]
@jozemlakar As far as I can see the failures are on SI codes, can you check out the log at [this line](https://github.com/eu-digital-green-certificates/dgc-testdata/pull/353/checks?check_run_id=2912511686#step:7:93) ?

**Comment by jozemlakar** [comment]
@daniel-eder  I am sorry but from the logs I cannot understand what the error is. config_env EXPECTED_RESULTS. Makes no sense to me. We might have made a mistake, but from the logs I cannot understand what the mistake is.

**Comment by daniel-eder** [comment]
@jozemlakar I'm not an expert on the schema, but if you compare [one of the files the test failed on](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/55ee5ec7ea5284b769e082dc9cbc4767ffddd6e7/SI/2DCode/raw/test-AG.json) to this [AT Test File](https://github.com/eu-digital-green-certificates/dgc-testdata/blob/4736b93c80597d77a283f5644714ed59b9e476bc/AT/2DCode/raw/1.json#L39) we see that in yours the key "EXPECTEDRESULTS" is missing, which matches error message.

**Comment by jozemlakar** [comment]
The JSON was made by NB, so did not include EXPECTEDRESULTS. Now added.

**Review by daniel-eder — APPROVED** [review]

**Pull request merged**
