### PR TITLE
Test data for LI

### PR DESCRIPTION
**Pull request by phuber**
recovery file, everything should work fine.

### CODE REVIEW

**Review by SchulzeStTSI — CHANGES_REQUESTED** [review]
@phuber the UVCI contains "NL" . The uvci must be in CI field not, in "is" field.

**Comment by phuber** [comment]
@SchulzeStTSI: I put all our test data into this single PR to make things easier.
The barcodes passed the integration test today and should be valid.

Could you please review this pull request again?

Thanks and best regards,
Patrick

**Review by SchulzeStTSI — CHANGES_REQUESTED** [review]
@phuber Thanks for merging it into one:) File 3 has still missing ci field and the wrong is field.

**Comment by daniel-eder** [comment]
@phuber due to a change in how the EHNs JSON schema URL works, the check for your PR currently fails. Could you update your branch to the latest main to incorporate the updated and working schema URL? Then we can see if there are any actual issues left. 

Thanks!

**Comment by phuber** [comment]
@SchulzeStTSI: I fixed the vaccination test, please have another look at it. 

@daniel-eder: I merged the current main branch into mine, so I hope the CI checks should be working now :-) If it does not work, I'll come back to you, maybe we could have a short call on the topic.

**Review by SchulzeStTSI — APPROVED** [review]

**Pull request merged**
